//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 03:13:40 PM ICT 
//


package com.viettel.ws.FORM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATTACHType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATTACHType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ATTACH_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ATTACH_DES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ATTACH_DATA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTACHType", propOrder = {
    "attachname",
    "attachdes",
    "attachdata"
})
public class ATTACHType {

    @XmlElement(name = "ATTACH_NAME", required = true)
    protected String attachname;
    @XmlElement(name = "ATTACH_DES", required = true)
    protected String attachdes;
    @XmlElement(name = "ATTACH_DATA", required = true)
    protected String attachdata;

    /**
     * Gets the value of the attachname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTACHNAME() {
        return attachname;
    }

    /**
     * Sets the value of the attachname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTACHNAME(String value) {
        this.attachname = value;
    }

    /**
     * Gets the value of the attachdes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTACHDES() {
        return attachdes;
    }

    /**
     * Sets the value of the attachdes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTACHDES(String value) {
        this.attachdes = value;
    }

    /**
     * Gets the value of the attachdata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTACHDATA() {
        return attachdata;
    }

    /**
     * Sets the value of the attachdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTACHDATA(String value) {
        this.attachdata = value;
    }

}
