//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 03:13:40 PM ICT 
//


package com.viettel.ws.FORM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FILEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FILEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FILE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FILE_LIST" type="{}FILE_LISTType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FILEType", propOrder = {
    "filecode",
    "filelist"
})
public class FILEType {

    @XmlElement(name = "FILE_CODE", required = true)
    protected String filecode;
    @XmlElement(name = "FILE_LIST", required = true)
    protected FILELISTType filelist;

    /**
     * Gets the value of the filecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILECODE() {
        return filecode;
    }

    /**
     * Sets the value of the filecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILECODE(String value) {
        this.filecode = value;
    }

    /**
     * Gets the value of the filelist property.
     * 
     * @return
     *     possible object is
     *     {@link FILELISTType }
     *     
     */
    public FILELISTType getFILELIST() {
        return filelist;
    }

    /**
     * Sets the value of the filelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link FILELISTType }
     *     
     */
    public void setFILELIST(FILELISTType value) {
        this.filelist = value;
    }

}
