//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 03:13:40 PM ICT 
//
package com.viettel.ws.FORM;

import com.viettel.hqmc.BO.MainlyTarget;
import com.viettel.hqmc.BO.ProductTarget;
import com.viettel.hqmc.BO.QualityControlPlan;
import com.viettel.hqmc.FORM.AnnouncementForm;
import com.viettel.hqmc.FORM.DetailProductForm;
import com.viettel.hqmc.FORM.FilesForm;
import com.viettel.voffice.database.BO.VoAttachs;
import static java.lang.Float.isNaN;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for FILE_ITEMSType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="FILE_ITEMSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FILE_ATTP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DEPT_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PROVINCE_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="BUSSINESS_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="BUSSINESS_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSSINESS_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSSINESS_FAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSSINESS_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSSINESS_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HS_CODE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="PRODUCT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PRODUCT_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MANUFACTURE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_FAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NATION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANNOUNCE_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANNOUNCE_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANNOUNCE_SIGN_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MATCHING_TARGET" type="{}MATCHING_TARGETType"/>
 *         &lt;element name="ANNOUNCE_METHOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SEND_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="USER_CREATE_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PRODUCT_DETAILS" type="{}PRODUCT_DETAILSType"/>
 *         &lt;element name="PRODUCT_MAINLY_TARGET" type="{}PRODUCT_MAINLY_TARGETType"/>
 *         &lt;element name="PRODUCT_BIO_TARGET" type="{}PRODUCT_BIO_TARGETType"/>
 *         &lt;element name="PRODUCT_HEAVY_METAL" type="{}PRODUCT_HEAVY_METALType"/>
 *         &lt;element name="PRODUCT_UNEX_CHEMICAL" type="{}PRODUCT_UNEX_CHEMICALType"/>
 *         &lt;element name="PRODUCT_PHYSIC_CHEMICAL" type="{}PRODUCT_PHYSIC_CHEMICALType"/>
 *         &lt;element name="QUALITY_CONTROL_PLAN" type="{}QUALITY_CONTROL_PLANType"/>
 *         &lt;element name="ATTACHMENTS" type="{}ATTACHMENTSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FILE_ITEMSType", propOrder = {
    "id",
    "fileattpcode",
    "type",
    "status",
    "deptid",
    "provinceid",
    "bussinessid",
    "bussinessname",
    "bussinessphone",
    "bussinessfax",
    "bussinessemail",
    "bussinessaddress",
    "hscode",
    "producttype",
    "productid",
    "productno",
    "manufacturename",
    "manufacturephone",
    "manufactureaddress",
    "manufactureemail",
    "manufacturefax",
    "nationcode",
    "announcenumber",
    "announcedate",
    "announcesignname",
    "matchingtarget",
    "announcemethod",
    "senddate",
    "usercreateid",
    "productdetails",
    "productmainlytarget",
    "productbiotarget",
    "productheavymetal",
    "productunexchemical",
    "productphysicchemical",
    "qualitycontrolplan",
    "attachments"
})
public class FILEITEMSType {

    @XmlElement(name = "ID")
    protected Long id;
    @XmlElement(name = "FILE_ATTP_CODE", required = true)
    protected String fileattpcode;
    @XmlElement(name = "TYPE", required = true)
    protected Long type;
    @XmlElement(name = "STATUS")
    protected Long status;
    @XmlElement(name = "DEPT_ID")
    protected Long deptid;
    @XmlElement(name = "PROVINCE_ID")
    protected int provinceid;
    @XmlElement(name = "BUSSINESS_ID")
    protected int bussinessid;
    @XmlElement(name = "BUSSINESS_NAME", required = true)
    protected String bussinessname;
    @XmlElement(name = "BUSSINESS_PHONE", required = true)
    protected String bussinessphone;
    @XmlElement(name = "BUSSINESS_FAX", required = true)
    protected String bussinessfax;
    @XmlElement(name = "BUSSINESS_EMAIL", required = true)
    protected String bussinessemail;
    @XmlElement(name = "BUSSINESS_ADDRESS", required = true)
    protected String bussinessaddress;
    @XmlElement(name = "HS_CODE", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar hscode;
    @XmlElement(name = "PRODUCT_TYPE", required = true)
    protected Long producttype;
    @XmlElement(name = "PRODUCT_ID")
    protected int productid;
    @XmlElement(name = "PRODUCT_NO")
    protected String productno;
    @XmlElement(name = "MANUFACTURE_NAME", required = true)
    protected String manufacturename;
    @XmlElement(name = "MANUFACTURE_PHONE", required = true)
    protected String manufacturephone;
    @XmlElement(name = "MANUFACTURE_ADDRESS", required = true)
    protected String manufactureaddress;
    @XmlElement(name = "MANUFACTURE_EMAIL", required = true)
    protected String manufactureemail;
    @XmlElement(name = "MANUFACTURE_FAX", required = true)
    protected String manufacturefax;
    @XmlElement(name = "NATION_CODE", required = true)
    protected String nationcode;
    @XmlElement(name = "ANNOUNCE_NUMBER", required = true)
    protected String announcenumber;
    @XmlElement(name = "ANNOUNCE_DATE", required = true)
    protected String announcedate;
    @XmlElement(name = "ANNOUNCE_SIGN_NAME", required = true)
    protected String announcesignname;
    @XmlElement(name = "MATCHING_TARGET", required = true)
    protected MATCHINGTARGETType matchingtarget;
    @XmlElement(name = "ANNOUNCE_METHOD", required = true)
    protected String announcemethod;
    @XmlElement(name = "SEND_DATE", required = true)
    protected String senddate;
    @XmlElement(name = "USER_CREATE_ID")
    protected Long usercreateid;
    @XmlElement(name = "PRODUCT_DETAILS", required = true)
    protected PRODUCTDETAILSType productdetails;
    @XmlElement(name = "PRODUCT_MAINLY_TARGET", required = true)
    protected PRODUCTMAINLYTARGETType productmainlytarget;
    @XmlElement(name = "PRODUCT_BIO_TARGET", required = true)
    protected PRODUCTBIOTARGETType productbiotarget;
    @XmlElement(name = "PRODUCT_HEAVY_METAL", required = true)
    protected PRODUCTHEAVYMETALType productheavymetal;
    @XmlElement(name = "PRODUCT_UNEX_CHEMICAL", required = true)
    protected PRODUCTUNEXCHEMICALType productunexchemical;
    @XmlElement(name = "PRODUCT_PHYSIC_CHEMICAL", required = true)
    protected PRODUCTPHYSICCHEMICALType productphysicchemical;
    @XmlElement(name = "QUALITY_CONTROL_PLAN", required = true)
    protected QUALITYCONTROLPLANType qualitycontrolplan;
    @XmlElement(name = "ATTACHMENTS", required = true)
    protected ATTACHMENTSType attachments;

    /**
     * Gets the value of the id property.
     *
     */
    public long getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     */
    public void setID(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the fileattpcode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFILEATTPCODE() {
        return fileattpcode;
    }

    /**
     * Sets the value of the fileattpcode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFILEATTPCODE(String value) {
        this.fileattpcode = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public Long getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTYPE(Long value) {
        this.type = value;
    }

    /**
     * Gets the value of the status property.
     *
     */
    public Long getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     */
    public void setSTATUS(Long value) {
        this.status = value;
    }

    /**
     * Gets the value of the deptid property.
     *
     */
    public Long getDEPTID() {
        return deptid;
    }

    /**
     * Sets the value of the deptid property.
     *
     */
    public void setDEPTID(Long value) {
        this.deptid = value;
    }

    /**
     * Gets the value of the provinceid property.
     *
     */
    public int getPROVINCEID() {
        return provinceid;
    }

    /**
     * Sets the value of the provinceid property.
     *
     */
    public void setPROVINCEID(int value) {
        this.provinceid = value;
    }

    /**
     * Gets the value of the bussinessid property.
     *
     */
    public int getBUSSINESSID() {
        return bussinessid;
    }

    /**
     * Sets the value of the bussinessid property.
     *
     */
    public void setBUSSINESSID(int value) {
        this.bussinessid = value;
    }

    /**
     * Gets the value of the bussinessname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSSINESSNAME() {
        return bussinessname;
    }

    /**
     * Sets the value of the bussinessname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSSINESSNAME(String value) {
        this.bussinessname = value;
    }

    /**
     * Gets the value of the bussinessphone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSSINESSPHONE() {
        return bussinessphone;
    }

    /**
     * Sets the value of the bussinessphone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSSINESSPHONE(String value) {
        this.bussinessphone = value;
    }

    /**
     * Gets the value of the bussinessfax property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSSINESSFAX() {
        return bussinessfax;
    }

    /**
     * Sets the value of the bussinessfax property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSSINESSFAX(String value) {
        this.bussinessfax = value;
    }

    /**
     * Gets the value of the bussinessemail property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSSINESSEMAIL() {
        return bussinessemail;
    }

    /**
     * Sets the value of the bussinessemail property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSSINESSEMAIL(String value) {
        this.bussinessemail = value;
    }

    /**
     * Gets the value of the bussinessaddress property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSSINESSADDRESS() {
        return bussinessaddress;
    }

    /**
     * Sets the value of the bussinessaddress property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSSINESSADDRESS(String value) {
        this.bussinessaddress = value;
    }

    /**
     * Gets the value of the hscode property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getHSCODE() {
        return hscode;
    }

    /**
     * Sets the value of the hscode property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setHSCODE(XMLGregorianCalendar value) {
        this.hscode = value;
    }

    /**
     * Gets the value of the producttype property.
     *
     * @return possible object is {@link String }
     *
     */
    public Long getPRODUCTTYPE() {
        return producttype;
    }

    /**
     * Sets the value of the producttype property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTTYPE(Long value) {
        this.producttype = value;
    }

    /**
     * Gets the value of the productid property.
     *
     */
    public int getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     *
     */
    public void setPRODUCTID(int value) {
        this.productid = value;
    }

    /**
     * Gets the value of the productno property.
     *
     */
    public String getPRODUCTNO() {
        return productno;
    }

    /**
     * Sets the value of the productno property.
     *
     */
    public void setPRODUCTNO(String value) {
        this.productno = value;
    }

    /**
     * Gets the value of the manufacturename property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTURENAME() {
        return manufacturename;
    }

    /**
     * Sets the value of the manufacturename property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTURENAME(String value) {
        this.manufacturename = value;
    }

    /**
     * Gets the value of the manufacturephone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREPHONE() {
        return manufacturephone;
    }

    /**
     * Sets the value of the manufacturephone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREPHONE(String value) {
        this.manufacturephone = value;
    }

    /**
     * Gets the value of the manufactureaddress property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREADDRESS() {
        return manufactureaddress;
    }

    /**
     * Sets the value of the manufactureaddress property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREADDRESS(String value) {
        this.manufactureaddress = value;
    }

    /**
     * Gets the value of the manufactureemail property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREEMAIL() {
        return manufactureemail;
    }

    /**
     * Sets the value of the manufactureemail property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREEMAIL(String value) {
        this.manufactureemail = value;
    }

    /**
     * Gets the value of the manufacturefax property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREFAX() {
        return manufacturefax;
    }

    /**
     * Sets the value of the manufacturefax property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREFAX(String value) {
        this.manufacturefax = value;
    }

    /**
     * Gets the value of the nationcode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNATIONCODE() {
        return nationcode;
    }

    /**
     * Sets the value of the nationcode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNATIONCODE(String value) {
        this.nationcode = value;
    }

    /**
     * Gets the value of the announcenumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCENUMBER() {
        return announcenumber;
    }

    /**
     * Sets the value of the announcenumber property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCENUMBER(String value) {
        this.announcenumber = value;
    }

    /**
     * Gets the value of the announcedate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCEDATE() {
        return announcedate;
    }

    /**
     * Sets the value of the announcedate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCEDATE(String value) {
        this.announcedate = value;
    }

    /**
     * Gets the value of the announcesignname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCESIGNNAME() {
        return announcesignname;
    }

    /**
     * Sets the value of the announcesignname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCESIGNNAME(String value) {
        this.announcesignname = value;
    }

    /**
     * Gets the value of the matchingtarget property.
     *
     * @return possible object is {@link MATCHINGTARGETType }
     *
     */
    public MATCHINGTARGETType getMATCHINGTARGET() {
        return matchingtarget;
    }

    /**
     * Sets the value of the matchingtarget property.
     *
     * @param value allowed object is {@link MATCHINGTARGETType }
     *
     */
    public void setMATCHINGTARGET(MATCHINGTARGETType value) {
        this.matchingtarget = value;
    }

    /**
     * Gets the value of the announcemethod property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCEMETHOD() {
        return announcemethod;
    }

    /**
     * Sets the value of the announcemethod property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCEMETHOD(String value) {
        this.announcemethod = value;
    }

    /**
     * Gets the value of the senddate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSENDDATE() {
        return senddate;
    }

    /**
     * Sets the value of the senddate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSENDDATE(String value) {
        this.senddate = value;
    }

    /**
     * Gets the value of the usercreateid property.
     *
     */
    public Long getUSERCREATEID() {
        return usercreateid;
    }

    /**
     * Sets the value of the usercreateid property.
     *
     */
    public void setUSERCREATEID(Long value) {
        this.usercreateid = value;
    }

    /**
     * Gets the value of the productdetails property.
     *
     * @return possible object is {@link PRODUCTDETAILSType }
     *
     */
    public PRODUCTDETAILSType getPRODUCTDETAILS() {
        return productdetails;
    }

    /**
     * Sets the value of the productdetails property.
     *
     * @param value allowed object is {@link PRODUCTDETAILSType }
     *
     */
    public void setPRODUCTDETAILS(PRODUCTDETAILSType value) {
        this.productdetails = value;
    }

    /**
     * Gets the value of the productmainlytarget property.
     *
     * @return possible object is {@link PRODUCTMAINLYTARGETType }
     *
     */
    public PRODUCTMAINLYTARGETType getPRODUCTMAINLYTARGET() {
        return productmainlytarget;
    }

    /**
     * Sets the value of the productmainlytarget property.
     *
     * @param value allowed object is {@link PRODUCTMAINLYTARGETType }
     *
     */
    public void setPRODUCTMAINLYTARGET(PRODUCTMAINLYTARGETType value) {
        this.productmainlytarget = value;
    }

    /**
     * Gets the value of the productbiotarget property.
     *
     * @return possible object is {@link PRODUCTBIOTARGETType }
     *
     */
    public PRODUCTBIOTARGETType getPRODUCTBIOTARGET() {
        return productbiotarget;
    }

    /**
     * Sets the value of the productbiotarget property.
     *
     * @param value allowed object is {@link PRODUCTBIOTARGETType }
     *
     */
    public void setPRODUCTBIOTARGET(PRODUCTBIOTARGETType value) {
        this.productbiotarget = value;
    }

    /**
     * Gets the value of the productheavymetal property.
     *
     * @return possible object is {@link PRODUCTHEAVYMETALType }
     *
     */
    public PRODUCTHEAVYMETALType getPRODUCTHEAVYMETAL() {
        return productheavymetal;
    }

    /**
     * Sets the value of the productheavymetal property.
     *
     * @param value allowed object is {@link PRODUCTHEAVYMETALType }
     *
     */
    public void setPRODUCTHEAVYMETAL(PRODUCTHEAVYMETALType value) {
        this.productheavymetal = value;
    }

    /**
     * Gets the value of the productunexchemical property.
     *
     * @return possible object is {@link PRODUCTUNEXCHEMICALType }
     *
     */
    public PRODUCTUNEXCHEMICALType getPRODUCTUNEXCHEMICAL() {
        return productunexchemical;
    }

    /**
     * Sets the value of the productunexchemical property.
     *
     * @param value allowed object is {@link PRODUCTUNEXCHEMICALType }
     *
     */
    public void setPRODUCTUNEXCHEMICAL(PRODUCTUNEXCHEMICALType value) {
        this.productunexchemical = value;
    }

    /**
     * Gets the value of the productphysicchemical property.
     *
     * @return possible object is {@link PRODUCTPHYSICCHEMICALType }
     *
     */
    public PRODUCTPHYSICCHEMICALType getPRODUCTPHYSICCHEMICAL() {
        return productphysicchemical;
    }

    /**
     * Sets the value of the productphysicchemical property.
     *
     * @param value allowed object is {@link PRODUCTPHYSICCHEMICALType }
     *
     */
    public void setPRODUCTPHYSICCHEMICAL(PRODUCTPHYSICCHEMICALType value) {
        this.productphysicchemical = value;
    }

    /**
     * Gets the value of the qualitycontrolplan property.
     *
     * @return possible object is {@link QUALITYCONTROLPLANType }
     *
     */
    public QUALITYCONTROLPLANType getQUALITYCONTROLPLAN() {
        return qualitycontrolplan;
    }

    /**
     * Sets the value of the qualitycontrolplan property.
     *
     * @param value allowed object is {@link QUALITYCONTROLPLANType }
     *
     */
    public void setQUALITYCONTROLPLAN(QUALITYCONTROLPLANType value) {
        this.qualitycontrolplan = value;
    }

    /**
     * Gets the value of the attachments property.
     *
     * @return possible object is {@link ATTACHMENTSType }
     *
     */
    public ATTACHMENTSType getATTACHMENTS() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     *
     * @param value allowed object is {@link ATTACHMENTSType }
     *
     */
    public void setATTACHMENTS(ATTACHMENTSType value) {
        this.attachments = value;
    }

    public FilesForm wsToForm() throws ParseException {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        FilesForm form = new FilesForm();
        form.setFileCode(fileattpcode);
        form.setSendDate(formatter.parse(senddate));
        form.setAnnouncement(new AnnouncementForm());
        form.getAnnouncement().setBusinessName(bussinessname);
        form.setDeptId(deptid);
        form.getAnnouncement().setBusinessAddress(bussinessaddress);
        form.getAnnouncement().setManufactureName(manufacturename);
        form.getAnnouncement().setManufactureAddress(manufactureaddress);
        form.getAnnouncement().setNationName(nationcode);
        form.getAnnouncement().setProductName("Keo");
        form.getAnnouncement().setMatchingTarget("QT01");
        form.setFileId(id);
        form.setFileTypeName("Cấp giấy tiếp nhận bản công bố hợp quy(bên thứ nhất)");
        //convert tim kiem trong db lay id file type
//        form.setFileType(TYPE);
        form.setFileType(type);
        //lay status trong 
        form.setStatus(status);
//        form.getAnnouncement().setAnnouncementId(21212132L);
        form.getAnnouncement().setBusinessEmail(bussinessemail);
        form.getAnnouncement().setBusinessFax(bussinessfax);
        form.getAnnouncement().setBusinessTelephone(bussinessphone);
        form.getAnnouncement().setManufactureEmail(manufactureemail);
        form.getAnnouncement().setManufactureFax(manufacturefax);
        form.getAnnouncement().setManufactureTel(manufacturephone);
        form.getAnnouncement().setAnnouncementNo(announcenumber);
        form.getAnnouncement().setAssessmentMethod(announcemethod);
        form.getAnnouncement().setPublishDate(formatter.parse(announcedate));
        form.getAnnouncement().setSigner(announcesignname);

        form.setDetailProduct(new DetailProductForm());
        form.getDetailProduct().setProductNo(productno);
        form.getDetailProduct().setProductType(producttype);

        form.getDetailProduct().setProductSmell(productdetails.getPRODUCTSMELL());
        form.getDetailProduct().setProductStatus(productdetails.getPRODUCTSTATUS());
        form.getDetailProduct().setProductColor(productdetails.getPRODUCTCOLOR());
        form.getDetailProduct().setProductOtherStatus(productdetails.getPRODUCTOTHERSTATUS());
        form.getDetailProduct().setComponents(productdetails.getCOMPONENTS());
        form.getDetailProduct().setTimeInUse(productdetails.getTIMEINUSE());
        form.getDetailProduct().setObjectUse(productdetails.getOBJECTUSAGE());
        form.getDetailProduct().setUseage(productdetails.getUSEAGE());
        form.getDetailProduct().setGuideline(productdetails.getGUIDELINE());
        form.getDetailProduct().setPreservation(productdetails.getPRESERVATION());
        form.getDetailProduct().setPackateMaterial(productdetails.getPACKATEMATERIAL());
        form.getDetailProduct().setProductionProcess(productdetails.getPRODUCTIONPROCESS());
        form.getDetailProduct().setCounterfeitDistinctive(productdetails.getPRODUCTCOMPARE());
        form.getDetailProduct().setProductTypeName("Rau Sach");
        //thieu product name
        //form.setProductName();
        //hien tai he thong dang de la string k phai danh muc
//        form.setMatchingTarget(MATCHING_TARGET);
        //hien tai he thong dang quan ly theo ten khong theo danh muc
        // mainly target
        List<MainlyTarget> lstMainlyTarget = new ArrayList<MainlyTarget>();
        for (TARGETMAINLYTARGETType bo : productmainlytarget.targetmainlytarget) {
            MainlyTarget temp = new MainlyTarget();
            temp.setMeetLevel(bo.getMEETLEVEL());
            temp.setTargetName(bo.getTARGETNAME());
            temp.setUnitId(bo.getUNITID());
            temp.setPublishLevel(bo.getPUBLISHLEVEL());
            temp.setUnitName("CFU/g");
            lstMainlyTarget.add(temp);
        }
        form.setLstMainlyTarget(lstMainlyTarget);

        //productbiotarget
        List<ProductTarget> lstBioTarget = new ArrayList<ProductTarget>();
        for (TARGETBIOTARGETType bo : productbiotarget.targetbiotarget) {
            ProductTarget temp = new ProductTarget();
            temp.setMaxLevel(bo.getMAXLEVEL());
            temp.setTargetName(bo.getTARGETNAME());
            temp.setUnitId(bo.getUNITID());
            temp.setUnitName("CFU/g");
            temp.setTargetType(1L);
            lstBioTarget.add(temp);
        }
        form.setLstBioTarget(lstBioTarget);

        // product_physical_chemical
        List<ProductTarget> lstChemical = new ArrayList<ProductTarget>();
        for (TARGETPHYSICCHEMICALType bo : productphysicchemical.targetphysicchemical) {
            ProductTarget temp = new ProductTarget();
            temp.setMaxLevel(bo.getMAXLEVEL());
            temp.setTargetName(bo.getTARGETNAME());
            temp.setUnitId(bo.getUNITID());
            temp.setUnitName("CFU/g");
            temp.setTargetType(3l);
            lstChemical.add(temp);
        }
        form.setLstChemical(lstChemical);
        //form.setMatchingTarget(null);

        //heavy metal
        List<ProductTarget> lstHeavyMetal = new ArrayList<ProductTarget>();
        for (TARGETHEAVYMETALType bo : productheavymetal.targetheavymetal) {
            ProductTarget temp = new ProductTarget();
            temp.setMaxLevel(bo.getMAXLEVEL());
            temp.setTargetName(bo.getTARGETNAME());
            temp.setUnitId(bo.getUNITID());
            temp.setUnitName("CFU/g");
            temp.setTargetType(2L);
            lstHeavyMetal.add(temp);
        }
        form.setLstHeavyMetal(lstHeavyMetal);

        // attach - pending
        List<VoAttachs> lstAttachs = new ArrayList<VoAttachs>();
        for (ATTACHType bo : attachments.attach) {
            VoAttachs temp = new VoAttachs();
            temp.setAttachDes(bo.getATTACHDES());
            temp.setAttachName(bo.getATTACHNAME());
            lstAttachs.add(temp);
        }
        form.setLstAttachs(null);

        //Quality control plan
        List<QualityControlPlan> lstQualityControl = new ArrayList<QualityControlPlan>();
        for (QUALITYType bo : qualitycontrolplan.quality) {
            QualityControlPlan temp = new QualityControlPlan();
            temp.setControlTarget(bo.getCONTROLTARGET());
            temp.setNoteForm(bo.getNOTEFORM());
            temp.setPatternFrequence(bo.getPATTERNFREQUENCE());
            temp.setProductProcessDetail(bo.getPRODUCTPROCESSDETAIL());
            temp.setTechnicalRegulation(bo.getTECHNICALREGULATION());
            temp.setTestDevice(bo.getTESTDEVICE());
            temp.setTestMethod(bo.getTESTMETHOD());
            lstQualityControl.add(temp);
        }
        form.setLstQualityControl(lstQualityControl);

        return form;
    }
      public boolean validatePhone(String phoneNumber) {
        boolean bReturn = true;
        if (phoneNumber == null) {
            bReturn = false;
        } else {
            phoneNumber = phoneNumber.trim();
            if (phoneNumber.length() > 14) {
                bReturn = false;
            } else {
                try {
                    bReturn = !isNaN(parseInt(phoneNumber));
                } catch (Exception en) {
                    bReturn = false;
                }
            }
        }
        return bReturn;
    }

    boolean isValidDate(String input) {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            format.parse(input);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    public List validate() throws ParseException {
        ERROR err;
        RESULT lstError = new RESULT();
        List error = null;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        FilesForm form = new FilesForm();
        lstError.setLstERROR(null);
        if (fileattpcode.length() > 10) {

//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (isValidDate(senddate) == false) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (bussinessname.length() > 255) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (deptid.toString().length() > 10) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (bussinessaddress.length() > 255) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (manufacturename.length() > 255) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (manufactureaddress.length() > 255) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (nationcode.length() > 10) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        form.getAnnouncement().setProductName("kotex");
        form.getAnnouncement().setMatchingTarget("QT01");
        if (id.toString().length() > 10) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        form.setFileTypeName("Cấp giấy tiếp nhận bản công bố hợp quy(bên thứ nhất)");
        //convert tim kiem trong db lay id file type
//        form.setFileType(TYPE);
        if (type.toString().length() > 50) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        //lay status trong 
        if (status.toString().length() > 10) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        if (bussinessemail.matches(EMAIL_REGEX) || bussinessemail.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (validatePhone(bussinessfax) == false || bussinessfax.length() > 15) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (validatePhone(bussinessphone) == false || bussinessphone.length() > 15) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (manufactureemail.matches(EMAIL_REGEX) || manufactureemail.length() > 150) {

//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);

        }
        if (validatePhone(manufacturefax) == false || manufacturefax.length() > 15) {

//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);

        }
        if (validatePhone(manufacturephone) == false || manufacturephone.length() > 15) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (announcenumber.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (announcemethod.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (isValidDate(announcedate) == false || announcedate.length() > 20) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (announcesignname.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productno.length() > 50) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (producttype.toString().length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.productsmell.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.productstatus.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (productdetails.productcolor.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (productdetails.productotherstatus.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.productstatus.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.components.length() > 500) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.timeinuse.length() > 150) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (productdetails.useage.length() > 500) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (productdetails.objectusage.length() > 500) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.guideline.length() > 500) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        if (productdetails.preservation.length() > 255) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.packatematerial.length() > 255) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.productionprocess.length() > 500) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }
        if (productdetails.productcompare.length() > 500) {
//            err = new ERROR();
//            err.setERROR_ID(0L);
//            err.setERROR_CODE("none");
//            err.setERROR_NAME("none");
//            lstError.getLstERROR().add(err);
        }

        form.getDetailProduct().setProductTypeName("Rau Sach");
        //thieu product name
        //form.setProductName();
        //hien tai he thong dang de la string k phai danh muc
//        form.setMatchingTarget(MATCHING_TARGET);
        //hien tai he thong dang quan ly theo ten khong theo danh muc
        // mainly target
        for (int i = 0; i < productmainlytarget.targetmainlytarget.size(); i++) {
            if (productmainlytarget.targetmainlytarget.get(i).meetlevel.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productmainlytarget.targetmainlytarget.get(i).targetname.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productmainlytarget.targetmainlytarget.get(i).unitid.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productmainlytarget.targetmainlytarget.get(i).publishlevel.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }

        }

        //productbiotarget
        for (int i = 0; i < productbiotarget.targetbiotarget.size(); i++) {
            if (productbiotarget.targetbiotarget.get(i).maxlevel.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productbiotarget.targetbiotarget.get(i).unitid.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productbiotarget.targetbiotarget.get(i).targetname.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
        }

        // product_physical_chemical
        for (int i = 0; i < productphysicchemical.targetphysicchemical.size(); i++) {
            if (productphysicchemical.targetphysicchemical.get(i).maxlevel.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productphysicchemical.targetphysicchemical.get(i).unitid.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productphysicchemical.targetphysicchemical.get(i).targetname.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }

        }

        //heavy metal
        for (int i = 0; i < productheavymetal.targetheavymetal.size(); i++) {
            if (productheavymetal.targetheavymetal.get(i).maxlevel.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productheavymetal.targetheavymetal.get(i).unitid.length() > 10) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
            if (productheavymetal.targetheavymetal.get(i).targetname.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
            }
        }

        // attach - pending
//        List<VoAttachs> lstAttachs = new ArrayList<VoAttachs>();
//        for (ATTACHType bo : attachments.attach) {
//            VoAttachs temp = new VoAttachs();
//            temp.setAttachDes(bo.getATTACHDES());
//            temp.setAttachName(bo.getATTACHNAME());
//            lstAttachs.add(temp);
//        }
//        form.setLstAttachs(null);
        //Quality control plan
        List<QualityControlPlan> lstQualityControl = new ArrayList<QualityControlPlan>();
        for (QUALITYType bo : qualitycontrolplan.quality) {
            QualityControlPlan temp = new QualityControlPlan();
            temp.setControlTarget(bo.getCONTROLTARGET());
            temp.setNoteForm(bo.getNOTEFORM());
            temp.setPatternFrequence(bo.getPATTERNFREQUENCE());
            temp.setProductProcessDetail(bo.getPRODUCTPROCESSDETAIL());
            temp.setTechnicalRegulation(bo.getTECHNICALREGULATION());
            temp.setTestDevice(bo.getTESTDEVICE());
            temp.setTestMethod(bo.getTESTMETHOD());
            lstQualityControl.add(temp);
        }
        form.setLstQualityControl(lstQualityControl);

        for (int i = 0; i < qualitycontrolplan.quality.size(); i++) {
//            if (qualitycontrolplan.quality.get(i).controltarget.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
//            if (qualitycontrolplan.quality.get(i).note.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
//            if (qualitycontrolplan.quality.get(i).testmethod.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
//            if (qualitycontrolplan.quality.get(i).testdevice.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
//            if (qualitycontrolplan.quality.get(i).technicalregulation.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
//            if (qualitycontrolplan.quality.get(i).productprocessdetail.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
//            if (qualitycontrolplan.quality.get(i).patternfrequence.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
//            if (qualitycontrolplan.quality.get(i).noteform.length() > 255) {
//                err = new ERROR();
//                err.setERROR_ID(0L);
//                err.setERROR_CODE("none");
//                err.setERROR_NAME("none");
//                lstError.getLstERROR().add(err);
//            }
        }
        error = lstError.getLstERROR();
        return error;
    }

}
