//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 03:13:40 PM ICT 
//


package com.viettel.ws.FORM;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FILE_QNAME = new QName("", "FILE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FILEType }
     * 
     */
    public FILEType createFILEType() {
        return new FILEType();
    }

    /**
     * Create an instance of {@link FILEITEMSType }
     * 
     */
    public FILEITEMSType createFILEITEMSType() {
        return new FILEITEMSType();
    }

    /**
     * Create an instance of {@link PRODUCTBIOTARGETType }
     * 
     */
    public PRODUCTBIOTARGETType createPRODUCTBIOTARGETType() {
        return new PRODUCTBIOTARGETType();
    }

    /**
     * Create an instance of {@link TARGETMAINLYTARGETType }
     * 
     */
    public TARGETMAINLYTARGETType createTARGETMAINLYTARGETType() {
        return new TARGETMAINLYTARGETType();
    }

    /**
     * Create an instance of {@link PRODUCTMAINLYTARGETType }
     * 
     */
    public PRODUCTMAINLYTARGETType createPRODUCTMAINLYTARGETType() {
        return new PRODUCTMAINLYTARGETType();
    }

    /**
     * Create an instance of {@link TARGETUNEXCHEMICALType }
     * 
     */
    public TARGETUNEXCHEMICALType createTARGETUNEXCHEMICALType() {
        return new TARGETUNEXCHEMICALType();
    }

    /**
     * Create an instance of {@link PRODUCTDETAILSType }
     * 
     */
    public PRODUCTDETAILSType createPRODUCTDETAILSType() {
        return new PRODUCTDETAILSType();
    }

    /**
     * Create an instance of {@link ATTACHMENTSType }
     * 
     */
    public ATTACHMENTSType createATTACHMENTSType() {
        return new ATTACHMENTSType();
    }

    /**
     * Create an instance of {@link QUALITYCONTROLPLANType }
     * 
     */
    public QUALITYCONTROLPLANType createQUALITYCONTROLPLANType() {
        return new QUALITYCONTROLPLANType();
    }

    /**
     * Create an instance of {@link TARGETBIOTARGETType }
     * 
     */
    public TARGETBIOTARGETType createTARGETBIOTARGETType() {
        return new TARGETBIOTARGETType();
    }

    /**
     * Create an instance of {@link PRODUCTHEAVYMETALType }
     * 
     */
    public PRODUCTHEAVYMETALType createPRODUCTHEAVYMETALType() {
        return new PRODUCTHEAVYMETALType();
    }

    /**
     * Create an instance of {@link TARGETHEAVYMETALType }
     * 
     */
    public TARGETHEAVYMETALType createTARGETHEAVYMETALType() {
        return new TARGETHEAVYMETALType();
    }

    /**
     * Create an instance of {@link QUALITYType }
     * 
     */
    public QUALITYType createQUALITYType() {
        return new QUALITYType();
    }

    /**
     * Create an instance of {@link PRODUCTUNEXCHEMICALType }
     * 
     */
    public PRODUCTUNEXCHEMICALType createPRODUCTUNEXCHEMICALType() {
        return new PRODUCTUNEXCHEMICALType();
    }

    /**
     * Create an instance of {@link TARGETPHYSICCHEMICALType }
     * 
     */
    public TARGETPHYSICCHEMICALType createTARGETPHYSICCHEMICALType() {
        return new TARGETPHYSICCHEMICALType();
    }

    /**
     * Create an instance of {@link MATCHINGTARGETType }
     * 
     */
    public MATCHINGTARGETType createMATCHINGTARGETType() {
        return new MATCHINGTARGETType();
    }

    /**
     * Create an instance of {@link PRODUCTPHYSICCHEMICALType }
     * 
     */
    public PRODUCTPHYSICCHEMICALType createPRODUCTPHYSICCHEMICALType() {
        return new PRODUCTPHYSICCHEMICALType();
    }

    /**
     * Create an instance of {@link TARGETType }
     * 
     */
    public TARGETType createTARGETType() {
        return new TARGETType();
    }

    /**
     * Create an instance of {@link FILELISTType }
     * 
     */
    public FILELISTType createFILELISTType() {
        return new FILELISTType();
    }

    /**
     * Create an instance of {@link ATTACHType }
     * 
     */
    public ATTACHType createATTACHType() {
        return new ATTACHType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FILEType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FILE")
    public JAXBElement<FILEType> createFILE(FILEType value) {
        return new JAXBElement<FILEType>(_FILE_QNAME, FILEType.class, null, value);
    }

}
