//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 03:13:40 PM ICT 
//
package com.viettel.ws.FORM;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PRODUCT_DETAILSType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PRODUCT_DETAILSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PRODUCT_SMELL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_COLOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_OTHER_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COMPONENTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TIME_IN_USE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OBJECT_USAGE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="USEAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GUIDELINE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRESERVATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PACKATE_MATERIAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCTION_PROCESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_COMPARE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRODUCT_DETAILSType", propOrder = {
    "productsmell",
    "productstatus",
    "productcolor",
    "productotherstatus",
    "components",
    "timeinuse",
    "objectusage",
    "useage",
    "guideline",
    "preservation",
    "packatematerial",
    "productionprocess",
    "productcompare"
  
})
public class PRODUCTDETAILSType {

    @XmlElement(name = "PRODUCT_SMELL", required = true)
    protected String productsmell;
    @XmlElement(name = "PRODUCT_STATUS", required = true)
    protected String productstatus;
    @XmlElement(name = "PRODUCT_COLOR", required = true)
    protected String productcolor;
    @XmlElement(name = "PRODUCT_OTHER_STATUS", required = true)
    protected String productotherstatus;
    @XmlElement(name = "COMPONENTS", required = true)
    protected String components;
    @XmlElement(name = "TIME_IN_USE", required = true)
    protected String timeinuse;
    @XmlElement(name = "OBJECT_USAGE", required = true)
    protected String objectusage;
    @XmlElement(name = "USEAGE", required = true)
    protected String useage;
    @XmlElement(name = "GUIDELINE", required = true)
    protected String guideline;
    @XmlElement(name = "PRESERVATION", required = true)
    protected String preservation;
    @XmlElement(name = "PACKATE_MATERIAL", required = true)
    protected String packatematerial;
    @XmlElement(name = "PRODUCTION_PROCESS", required = true)
    protected String productionprocess;
    @XmlElement(name = "PRODUCT_COMPARE", required = true)
    protected String productcompare;


    /**
     * Gets the value of the productsmell property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTSMELL() {
        return productsmell;
    }

    /**
     * Sets the value of the productsmell property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTSMELL(String value) {
        this.productsmell = value;
    }

    /**
     * Gets the value of the productstatus property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTSTATUS() {
        return productstatus;
    }

    /**
     * Sets the value of the productstatus property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTSTATUS(String value) {
        this.productstatus = value;
    }

    /**
     * Gets the value of the productcolor property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTCOLOR() {
        return productcolor;
    }

    /**
     * Sets the value of the productcolor property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTCOLOR(String value) {
        this.productcolor = value;
    }

    /**
     * Gets the value of the productotherstatus property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTOTHERSTATUS() {
        return productotherstatus;
    }

    /**
     * Sets the value of the productotherstatus property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTOTHERSTATUS(String value) {
        this.productotherstatus = value;
    }

    /**
     * Gets the value of the components property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCOMPONENTS() {
        return components;
    }

    /**
     * Sets the value of the components property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCOMPONENTS(String value) {
        this.components = value;
    }

    /**
     * Gets the value of the timeinuse property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTIMEINUSE() {
        return timeinuse;
    }

    /**
     * Sets the value of the timeinuse property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTIMEINUSE(String value) {
        this.timeinuse = value;
    }

    /**
     * Gets the value of the objectusage property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public String getOBJECTUSAGE() {
        return objectusage;
    }

    /**
     * Sets the value of the objectusage property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setOBJECTUSAGE(String value) {
        this.objectusage = value;
    }

    /**
     * Gets the value of the useage property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUSEAGE() {
        return useage;
    }

    /**
     * Sets the value of the useage property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUSEAGE(String value) {
        this.useage = value;
    }

    /**
     * Gets the value of the guideline property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGUIDELINE() {
        return guideline;
    }

    /**
     * Sets the value of the guideline property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGUIDELINE(String value) {
        this.guideline = value;
    }

    /**
     * Gets the value of the preservation property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRESERVATION() {
        return preservation;
    }

    /**
     * Sets the value of the preservation property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRESERVATION(String value) {
        this.preservation = value;
    }

    /**
     * Gets the value of the packatematerial property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPACKATEMATERIAL() {
        return packatematerial;
    }

    /**
     * Sets the value of the packatematerial property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPACKATEMATERIAL(String value) {
        this.packatematerial = value;
    }

    /**
     * Gets the value of the productionprocess property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTIONPROCESS() {
        return productionprocess;
    }

    /**
     * Sets the value of the productionprocess property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTIONPROCESS(String value) {
        this.productionprocess = value;
    }

    /**
     * Gets the value of the productcompare property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTCOMPARE() {
        return productcompare;
    }

    /**
     * Sets the value of the productcompare property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTCOMPARE(String value) {
        this.productcompare = value;
    }



}
