//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.04 at 10:52:42 AM ICT
//
package com.viettel.ws.ANNOUCERECEIVE;

import com.viettel.hqmc.BO.MainlyTarget;
import com.viettel.hqmc.BO.Procedure;
import com.viettel.hqmc.BO.ProductTarget;
import com.viettel.hqmc.DAOHE.ProcedureDAOHE;
import com.viettel.hqmc.FORM.AnnouncementForm;
import com.viettel.hqmc.FORM.DetailProductForm;
import com.viettel.hqmc.FORM.FilesForm;
import com.viettel.voffice.database.BO.Category;
import com.viettel.voffice.database.DAOHibernate.CategoryDAOHE;
import com.viettel.vsaadmin.database.BO.Users;
import com.viettel.vsaadmin.database.DAOHibernate.UsersDAOHE;
import com.viettel.ws.validateData.Helper;
import com.viettel.ws.validateData.Validator;
import java.io.IOException;
import java.lang.reflect.Field;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 * <p>
 * Java class for ANNOUNCESENDDtoType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ANNOUNCESENDDtoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AUTHENTICATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="COMPONENTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TIME_IN_USE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OBJECT_USAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="USEAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GUIDELINE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PACKATE_MATERIAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCTION_PROCESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_COMPARE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NSW_FILE_CODE" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="IS_DELETED" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="FILE_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="DEPT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSSINESS_CODE" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="BUSINESS_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_FAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HS_CODE" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="PRODUCT_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_FAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REGION_FROM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANNOUNCE_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANNOUNCE_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ANNOUNCE_SIGN_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANNOUNCE_METHOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SEND_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="PRODUCT_SMELL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_COLOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_OTHER_STATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ANNOUNCE_SIGN_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CREATE_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CREATED_BY" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="MODIFY_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="MODIFIED_BY" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="MATCHING_TARGET_LIST" type="{}MATCHING_TARGET_LISTType"/>
 *         &lt;element name="MAINLY_TARGETS_LIST" type="{}MAINLY_TARGETS_LISTType"/>
 *         &lt;element name="BIO_TARGET_LIST" type="{}BIO_TARGET_LISTType"/>
 *         &lt;element name="HEAVY_METAL_LIST" type="{}HEAVY_METAL_LISTType"/>
 *         &lt;element name="UNEX_CHEMICAL_LIST" type="{}UNEX_CHEMICAL_LISTType"/>
 *         &lt;element name="IMPACT_TARGETS_LIST" type="{}IMPACT_TARGETS_LISTType"/>
 *         &lt;element name="QUALITY_CONTROL_PLAN" type="{}QUALITY_CONTROL_PLANType"/>
 *         &lt;element name="ATTACHMENTS" type="{}ATTACHMENTSType"/>
 *         &lt;element name="Signature" type="{}SignatureType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ANNOUNCESENDDtoType", propOrder = {
    "authenticate",
    "id",
    "fileType",
    "isFee",
    "components",
    "timeinuse",
    "objectusage",
    "useage",
    "guideline",
    "packatematerial",
    "productionprocess",
    "productcompare",
    "nswfilecode",
    "isdeleted",
    "filetypecode",
    "statuscode",
    "deptcode",
    "bussinesscode",
    "businessname",
    "businessaddress",
    "businessphone",
    "businessfax",
    "businessemail",
    "hscode",
    "producttypecode",
    "productname",
    "productno",
    "manufacturename",
    "manufacturephone",
    "manufactureaddress",
    "manufactureemail",
    "manufacturefax",
    "regionfrom",
    "announcenumber",
    "announcedate",
    "announcesignname",
    "announcemethod",
    "senddate",
    "productsmell",
    "productstatus",
    "productcolor",
    "productdetailtypecode",
    "productotherstate",
    "origin",
    "announcesigndate",
    "createdate",
    "createdby",
    "modifydate",
    "modifiedby",
    "matchingtargetlist",
    "matchingtarget",
    "mainlytargetslist",
    "biotargetlist",
    "heavymetallist",
    "unexchemicallist",
    "impacttargetslist",
    "qualitycontrolplan",
    "attachments",
    "signature"
})
public class ANNOUNCESENDDtoType {

    @XmlElement(name = "AUTHENTICATE")
    public String authenticate;
    @XmlElement(name = "ID")
    public String id;
    @XmlElement(name = "FILE_TYPE")
    public String fileType;
    @XmlElement(name = "IS_FEE")
    public String isFee;
    @XmlElement(name = "COMPONENTS")
    public String components;
    @XmlElement(name = "TIME_IN_USE")
    public String timeinuse;
    @XmlElement(name = "OBJECT_USAGE")
    public String objectusage;
    @XmlElement(name = "USEAGE")
    public String useage;
    @XmlElement(name = "GUIDELINE")
    public String guideline;
    @XmlElement(name = "PACKATE_MATERIAL")
    public String packatematerial;
    @XmlElement(name = "PRODUCTION_PROCESS")
    public String productionprocess;
    @XmlElement(name = "PRODUCT_COMPARE")
    public String productcompare;
    @XmlElement(name = "NSW_FILE_CODE")
    public String nswfilecode;
    @XmlElement(name = "IS_DELETED1")
    public String isdeleted;
    @XmlElement(name = "FILE_TYPE_CODE")
    public String filetypecode;
    @XmlElement(name = "STATUS_CODE")
    public String statuscode;
    @XmlElement(name = "DEPT_CODE")
    public String deptcode;
    @XmlElement(name = "BUSSINESS_CODE")
    public String bussinesscode;
    @XmlElement(name = "BUSINESS_NAME")
    public String businessname;
    @XmlElement(name = "BUSINESS_ADDRESS")
    public String businessaddress;
    @XmlElement(name = "BUSINESS_PHONE")
    public String businessphone;
    @XmlElement(name = "BUSINESS_FAX")
    public String businessfax;
    @XmlElement(name = "BUSINESS_EMAIL")
    public String businessemail;
    @XmlElement(name = "HS_CODE")
    public String hscode;
    @XmlElement(name = "PRODUCT_TYPE_CODE")
    public String producttypecode;
    @XmlElement(name = "PRODUCT_NAME")
    public String productname;
    @XmlElement(name = "PRODUCT_NO")
    public String productno;
    @XmlElement(name = "MANUFACTURE_NAME")
    public String manufacturename;
    @XmlElement(name = "MANUFACTURE_PHONE")
    public String manufacturephone;
    @XmlElement(name = "MANUFACTURE_ADDRESS")
    public String manufactureaddress;
    @XmlElement(name = "MANUFACTURE_EMAIL")
    public String manufactureemail;
    @XmlElement(name = "MANUFACTURE_FAX")
    public String manufacturefax;
    @XmlElement(name = "REGION_FROM")
    public String regionfrom;
    @XmlElement(name = "ANNOUNCE_NUMBER")
    public String announcenumber;
    @XmlElement(name = "ANNOUNCE_DATE")
    @XmlSchemaType(name = "dateTime")
    public String announcedate;
    @XmlElement(name = "ANNOUNCE_SIGN_NAME")
    public String announcesignname;
    @XmlElement(name = "ANNOUNCE_METHOD")
    public String announcemethod;
    @XmlElement(name = "SEND_DATE")
    @XmlSchemaType(name = "dateTime")
    public String senddate;
    @XmlElement(name = "PRODUCT_SMELL")
    public String productsmell;
    @XmlElement(name = "PRODUCT_STATUS")
    public String productstatus;
    @XmlElement(name = "PRODUCT_COLOR")
    public String productcolor;
    @XmlElement(name = "PRODUCT_DETAIL_TYPE_CODE")
    public String productdetailtypecode;
    @XmlElement(name = "PRODUCT_OTHER_STATE")
    public String productotherstate;
    @XmlElement(name = "ORIGIN")
    public String origin;
    @XmlElement(name = "ANNOUNCE_SIGN_DATE")
    @XmlSchemaType(name = "dateTime")
    public String announcesigndate;
    @XmlElement(name = "CREATE_DATE")
    @XmlSchemaType(name = "dateTime")
    public String createdate;
    @XmlElement(name = "CREATED_BY")
    public String createdby;
    @XmlElement(name = "MODIFY_DATE")
    @XmlSchemaType(name = "dateTime")
    public String modifydate;
    @XmlElement(name = "MODIFIED_BY")
    public String modifiedby;
    @XmlElement(name = "MATCHING_TARGET_LIST")
    public MATCHINGTARGETLISTType matchingtargetlist;
    @XmlElement(name = "MATCHING_TARGET")
    public String matchingtarget;
    @XmlElement(name = "MAINLY_TARGETS_LIST")
    public MAINLYTARGETSLISTType mainlytargetslist;
    @XmlElement(name = "BIO_TARGET_LIST")
    public BIOTARGETLISTType biotargetlist;
    @XmlElement(name = "HEAVY_METAL_LIST")
    public HEAVYMETALLISTType heavymetallist;
    @XmlElement(name = "UNEX_CHEMICAL_LIST")
    public UNEXCHEMICALLISTType unexchemicallist;
    @XmlElement(name = "IMPACT_TARGETS_LIST")
    public IMPACTTARGETSLISTType impacttargetslist;
    @XmlElement(name = "QUALITY_CONTROL_PLAN")
    public QUALITYCONTROLPLANType qualitycontrolplan;
    @XmlElement(name = "ATTACHMENTS")
    public ATTACHMENTSType attachments;
    @XmlElement(name = "Signature")
    public SignatureType signature;

    /**
     * Gets the value of the authenticate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAUTHENTICATE() {
        return authenticate;
    }

    /**
     * Sets the value of the authenticate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAUTHENTICATE(String value) {
        this.authenticate = value;
    }

    /**
     * Gets the value of the id property.
     *
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     */
    public void setPRODUCTDETAILTYPECODE(String value) {
        this.productdetailtypecode = value;
    }

    public String getPRODUCTDETAILTYPECODE() {
        return productdetailtypecode;
    }

    /**
     * Sets the value of the id property.
     *
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the components property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCOMPONENTS() {
        return components;
    }

    /**
     * Sets the value of the components property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCOMPONENTS(String value) {
        this.components = value;
    }

    /**
     * Gets the value of the timeinuse property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTIMEINUSE() {
        return timeinuse;
    }

    /**
     * Sets the value of the timeinuse property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTIMEINUSE(String value) {
        this.timeinuse = value;
    }

    /**
     * Gets the value of the objectusage property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOBJECTUSAGE() {
        return objectusage;
    }

    /**
     * Sets the value of the objectusage property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setOBJECTUSAGE(String value) {
        this.objectusage = value;
    }

    /**
     * Gets the value of the useage property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUSEAGE() {
        return useage;
    }

    /**
     * Sets the value of the useage property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUSEAGE(String value) {
        this.useage = value;
    }

    /**
     * Gets the value of the guideline property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGUIDELINE() {
        return guideline;
    }

    /**
     * Sets the value of the guideline property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGUIDELINE(String value) {
        this.guideline = value;
    }

    /**
     * Gets the value of the packatematerial property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPACKATEMATERIAL() {
        return packatematerial;
    }

    /**
     * Sets the value of the packatematerial property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPACKATEMATERIAL(String value) {
        this.packatematerial = value;
    }

    /**
     * Gets the value of the productionprocess property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTIONPROCESS() {
        return productionprocess;
    }

    /**
     * Sets the value of the productionprocess property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTIONPROCESS(String value) {
        this.productionprocess = value;
    }

    /**
     * Gets the value of the productcompare property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTCOMPARE() {
        return productcompare;
    }

    /**
     * Sets the value of the productcompare property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTCOMPARE(String value) {
        this.productcompare = value;
    }

    /**
     * Gets the value of the nswfilecode property.
     *
     */
    public String getNSWFILECODE() {
        return nswfilecode;
    }

    /**
     * Sets the value of the nswfilecode property.
     *
     */
    public void setNSWFILECODE(String value) {
        this.nswfilecode = value;
    }

    /**
     * Gets the value of the isdeleted property.
     *
     */
    public String getISDELETED() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     *
     */
    public void setISDELETED(String value) {
        this.isdeleted = value;
    }

    /**
     * Gets the value of the filetypecode property.
     *
     */
    public String getFILETYPECODE() {
        return filetypecode;
    }

    /**
     * Sets the value of the filetypecode property.
     *
     */
    public void setFILETYPECODE(String value) {
        this.filetypecode = value;
    }

    /**
     * Gets the value of the statuscode property.
     *
     */
    public String getSTATUSCODE() {
        return statuscode;
    }

    /**
     * Sets the value of the statuscode property.
     *
     */
    public void setSTATUSCODE(String value) {
        this.statuscode = value;
    }

    /**
     * Gets the value of the deptcode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDEPTCODE() {
        return deptcode;
    }

    /**
     * Sets the value of the deptcode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDEPTCODE(String value) {
        this.deptcode = value;
    }

    /**
     * Gets the value of the bussinesscode property.
     *
     */
    public String getBUSSINESSCODE() {
        return bussinesscode;
    }

    /**
     * Sets the value of the bussinesscode property.
     *
     */
    public void setBUSSINESSCODE(String value) {
        this.bussinesscode = value;
    }

    /**
     * Gets the value of the businessname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSINESSNAME() {
        return businessname;
    }

    /**
     * Sets the value of the businessname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSINESSNAME(String value) {
        this.businessname = value;
    }

    /**
     * Gets the value of the businessaddress property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSINESSADDRESS() {
        return businessaddress;
    }

    /**
     * Sets the value of the businessaddress property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSINESSADDRESS(String value) {
        this.businessaddress = value;
    }

    /**
     * Gets the value of the businessphone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSINESSPHONE() {
        return businessphone;
    }

    /**
     * Sets the value of the businessphone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSINESSPHONE(String value) {
        this.businessphone = value;
    }

    /**
     * Gets the value of the businessfax property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSINESSFAX() {
        return businessfax;
    }

    /**
     * Sets the value of the businessfax property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSINESSFAX(String value) {
        this.businessfax = value;
    }

    /**
     * Gets the value of the businessemail property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBUSINESSEMAIL() {
        return businessemail;
    }

    /**
     * Sets the value of the businessemail property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBUSINESSEMAIL(String value) {
        this.businessemail = value;
    }

    /**
     * Gets the value of the hscode property.
     *
     */
    public String getHSCODE() {
        return hscode;
    }

    /**
     * Sets the value of the hscode property.
     *
     */
    public void setHSCODE(String value) {
        this.hscode = value;
    }

    /**
     * Gets the value of the producttypecode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTTYPECODE() {
        return producttypecode;
    }

    /**
     * Sets the value of the producttypecode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTTYPECODE(String value) {
        this.producttypecode = value;
    }

    /**
     * Gets the value of the productname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTNAME() {
        return productname;
    }

    /**
     * Sets the value of the productname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTNAME(String value) {
        this.productname = value;
    }

    /**
     * Gets the value of the productno property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTNO() {
        return productno;
    }

    /**
     * Sets the value of the productno property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTNO(String value) {
        this.productno = value;
    }

    /**
     * Gets the value of the manufacturename property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTURENAME() {
        return manufacturename;
    }

    /**
     * Sets the value of the manufacturename property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTURENAME(String value) {
        this.manufacturename = value;
    }

    /**
     * Gets the value of the manufacturephone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREPHONE() {
        return manufacturephone;
    }

    /**
     * Sets the value of the manufacturephone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREPHONE(String value) {
        this.manufacturephone = value;
    }

    /**
     * Gets the value of the manufactureaddress property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREADDRESS() {
        return manufactureaddress;
    }

    /**
     * Sets the value of the manufactureaddress property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREADDRESS(String value) {
        this.manufactureaddress = value;
    }

    /**
     * Gets the value of the manufactureemail property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREEMAIL() {
        return manufactureemail;
    }

    /**
     * Sets the value of the manufactureemail property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREEMAIL(String value) {
        this.manufactureemail = value;
    }

    /**
     * Gets the value of the manufacturefax property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMANUFACTUREFAX() {
        return manufacturefax;
    }

    /**
     * Sets the value of the manufacturefax property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMANUFACTUREFAX(String value) {
        this.manufacturefax = value;
    }

    /**
     * Gets the value of the regionfrom property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getREGIONFROM() {
        return regionfrom;
    }

    /**
     * Sets the value of the regionfrom property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setREGIONFROM(String value) {
        this.regionfrom = value;
    }

    /**
     * Gets the value of the announcenumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCENUMBER() {
        return announcenumber;
    }

    /**
     * Sets the value of the announcenumber property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCENUMBER(String value) {
        this.announcenumber = value;
    }

    /**
     * Gets the value of the announcedate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCEDATE() {
        return announcedate;
    }

    /**
     * Sets the value of the announcedate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCEDATE(String value) {
        this.announcedate = value;
    }

    /**
     * Gets the value of the announcesignname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCESIGNNAME() {
        return announcesignname;
    }

    /**
     * Sets the value of the announcesignname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCESIGNNAME(String value) {
        this.announcesignname = value;
    }

    /**
     * Gets the value of the announcemethod property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCEMETHOD() {
        return announcemethod;
    }

    /**
     * Sets the value of the announcemethod property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCEMETHOD(String value) {
        this.announcemethod = value;
    }

    /**
     * Gets the value of the senddate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSENDDATE() {
        return senddate;
    }

    /**
     * Sets the value of the senddate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSENDDATE(String value) {
        this.senddate = value;
    }

    /**
     * Gets the value of the productsmell property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTSMELL() {
        return productsmell;
    }

    /**
     * Sets the value of the productsmell property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTSMELL(String value) {
        this.productsmell = value;
    }

    /**
     * Gets the value of the productstatus property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTSTATUS() {
        return productstatus;
    }

    /**
     * Sets the value of the productstatus property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTSTATUS(String value) {
        this.productstatus = value;
    }

    /**
     * Gets the value of the productcolor property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTCOLOR() {
        return productcolor;
    }

    /**
     * Sets the value of the productcolor property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTCOLOR(String value) {
        this.productcolor = value;
    }

    /**
     * Gets the value of the productotherstate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPRODUCTOTHERSTATE() {
        return productotherstate;
    }

    /**
     * Sets the value of the productotherstate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPRODUCTOTHERSTATE(String value) {
        this.productotherstate = value;
    }

    /**
     * Gets the value of the announcesigndate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getANNOUNCESIGNDATE() {
        return announcesigndate;
    }

    /**
     * Sets the value of the announcesigndate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setANNOUNCESIGNDATE(String value) {
        this.announcesigndate = value;
    }

    /**
     * Gets the value of the createdate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCREATEDATE() {
        return createdate;
    }

    /**
     * Sets the value of the createdate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCREATEDATE(String value) {
        this.createdate = value;
    }

    /**
     * Gets the value of the createdby property.
     *
     */
    public String getCREATEDBY() {
        return createdby;
    }

    /**
     * Sets the value of the createdby property.
     *
     */
    public void setCREATEDBY(String value) {
        this.createdby = value;
    }

    /**
     * Gets the value of the modifydate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMODIFYDATE() {
        return modifydate;
    }

    /**
     * Sets the value of the modifydate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMODIFYDATE(String value) {
        this.modifydate = value;
    }

    /**
     * Gets the value of the modifiedby property.
     *
     */
    public String getMODIFIEDBY() {
        return modifiedby;
    }

    /**
     * Sets the value of the modifiedby property.
     *
     */
    public void setMODIFIEDBY(String value) {
        this.modifiedby = value;
    }

    /**
     * Gets the value of the matchingtargetlist property.
     *
     * @return possible object is {@link MATCHINGTARGETLISTType }
     *
     */
    public MATCHINGTARGETLISTType getMATCHINGTARGETLIST() {
        return matchingtargetlist;
    }

    /**
     * Sets the value of the matchingtargetlist property.
     *
     * @param value allowed object is {@link MATCHINGTARGETLISTType }
     *
     */
    public void setMATCHINGTARGETLIST(MATCHINGTARGETLISTType value) {
        this.matchingtargetlist = value;
    }

    /**
     * Gets the value of the mainlytargetslist property.
     *
     * @return possible object is {@link MAINLYTARGETSLISTType }
     *
     */
    public MAINLYTARGETSLISTType getMAINLYTARGETSLIST() {
        return mainlytargetslist;
    }

    /**
     * Sets the value of the mainlytargetslist property.
     *
     * @param value allowed object is {@link MAINLYTARGETSLISTType }
     *
     */
    public void setMAINLYTARGETSLIST(MAINLYTARGETSLISTType value) {
        this.mainlytargetslist = value;
    }

    /**
     * Gets the value of the biotargetlist property.
     *
     * @return possible object is {@link BIOTARGETLISTType }
     *
     */
    public BIOTARGETLISTType getBIOTARGETLIST() {
        return biotargetlist;
    }

    /**
     * Sets the value of the biotargetlist property.
     *
     * @param value allowed object is {@link BIOTARGETLISTType }
     *
     */
    public void setBIOTARGETLIST(BIOTARGETLISTType value) {
        this.biotargetlist = value;
    }

    /**
     * Gets the value of the heavymetallist property.
     *
     * @return possible object is {@link HEAVYMETALLISTType }
     *
     */
    public HEAVYMETALLISTType getHEAVYMETALLIST() {
        return heavymetallist;
    }

    /**
     * Sets the value of the heavymetallist property.
     *
     * @param value allowed object is {@link HEAVYMETALLISTType }
     *
     */
    public void setHEAVYMETALLIST(HEAVYMETALLISTType value) {
        this.heavymetallist = value;
    }

    /**
     * Gets the value of the unexchemicallist property.
     *
     * @return possible object is {@link UNEXCHEMICALLISTType }
     *
     */
    public UNEXCHEMICALLISTType getUNEXCHEMICALLIST() {
        return unexchemicallist;
    }

    /**
     * Sets the value of the unexchemicallist property.
     *
     * @param value allowed object is {@link UNEXCHEMICALLISTType }
     *
     */
    public void setUNEXCHEMICALLIST(UNEXCHEMICALLISTType value) {
        this.unexchemicallist = value;
    }

    /**
     * Gets the value of the impacttargetslist property.
     *
     * @return possible object is {@link IMPACTTARGETSLISTType }
     *
     */
    public IMPACTTARGETSLISTType getIMPACTTARGETSLIST() {
        return impacttargetslist;
    }

    /**
     * Sets the value of the impacttargetslist property.
     *
     * @param value allowed object is {@link IMPACTTARGETSLISTType }
     *
     */
    public void setIMPACTTARGETSLIST(IMPACTTARGETSLISTType value) {
        this.impacttargetslist = value;
    }

    /**
     * Gets the value of the qualitycontrolplan property.
     *
     * @return possible object is {@link QUALITYCONTROLPLANType }
     *
     */
    public QUALITYCONTROLPLANType getQUALITYCONTROLPLAN() {
        return qualitycontrolplan;
    }

    /**
     * Sets the value of the qualitycontrolplan property.
     *
     * @param value allowed object is {@link QUALITYCONTROLPLANType }
     *
     */
    public void setQUALITYCONTROLPLAN(QUALITYCONTROLPLANType value) {
        this.qualitycontrolplan = value;
    }

    /**
     * Gets the value of the attachments property.
     *
     * @return possible object is {@link ATTACHMENTSType }
     *
     */
    public ATTACHMENTSType getATTACHMENTS() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     *
     * @param value allowed object is {@link ATTACHMENTSType }
     *
     */
    public void setATTACHMENTS(ATTACHMENTSType value) {
        this.attachments = value;
    }

    /**
     * Gets the value of the signature property.
     *
     * @return possible object is {@link SignatureType }
     *
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     *
     * @param value allowed object is {@link SignatureType }
     *
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    public FilesForm wsToForm() throws ParseException, ParserConfigurationException, SAXException, IOException, ClassNotFoundException, SQLException {
        Helper hp = new Helper();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        FilesForm form = new FilesForm();
        form.setAnnouncement(new AnnouncementForm());
        //form.setFileId(id);
        //form.setFileCode();
//        form.setFileTypeName("Cấp giấy tiếp nhận bản công bố hợp quy(bên thứ nhất)");
        //convert tim kiem trong db lay id file type
//        form.setFileType(TYPE);
        ProcedureDAOHE proDaohe = new ProcedureDAOHE();
        Procedure proBo = null;
        try {
            proBo = proDaohe.getProcedureByDescription(fileType);
            if (proBo != null) {
                form.setFileType(proBo.getProcedureId());
                form.setFileTypeName(proBo.getName());
            }
        } catch (Exception ex) {
            Logger.getLogger(ANNOUNCESENDDtoType.class.getName()).log(Level.SEVERE, null, ex);
        }
        CategoryDAOHE cateDaohe = new CategoryDAOHE();
        Category cateBo = cateDaohe.findCategoryByTypeAndCode("SP", producttypecode);
        if (cateBo != null) {
            form.setProductTypeId(cateBo.getCategoryId());
            form.setProductTypeName(cateBo.getName());
        }
        if (!senddate.isEmpty()) {
            form.setSendDate(formatter.parse(senddate.substring(0, 10)));
        }
        form.setIsActive(Long.getLong(isdeleted));
        //  bat buoc
        form.setIsFee(Long.parseLong(isFee));
//        form.setFileType(Long.parseLong(fileType));
        form.setBusinessAddress(businessaddress);
        form.setBusinessName(businessname);
        form.setDeptId(Long.parseLong("1"));
        form.setUserCreateId(8171804l);
//        form.setAgencyId(Long.MAX_VALUE);

        form.getAnnouncement().setBusinessName(businessname);
        form.getAnnouncement().setBusinessAddress(businessaddress);
        form.getAnnouncement().setManufactureName(manufacturename);
        form.getAnnouncement().setManufactureAddress(manufactureaddress);
        form.getAnnouncement().setNationName(regionfrom);
        form.getAnnouncement().setProductName(productname);
//        CategoryDAOHE daoHE = new CategoryDAOHE();
//        List lst = daoHE.findAll();
//        String m_name = hp.getMATCHINGTARGET_NAME(matchingtargetlist.getMATCHINGTARGETDto());
//        form.getAnnouncement().setMatchingTarget(m_name);
        ProcedureDAOHE pd = new ProcedureDAOHE();
//        form.setFileType(pd.getByProperty("code", filetypecode).get(0).getProcedureId());//err
        //lay status trong
        form.setStatus(Long.parseLong(statuscode));
        form.setUserCreateId(Long.parseLong(createdby));
        if (form.getUserCreateId() != null) {
            UsersDAOHE udaohe = new UsersDAOHE();
            Users ubo = udaohe.findById(form.getUserCreateId());
            if (ubo != null) {
                form.setUserCreateName(ubo.getFullName());
                form.setDeptId(ubo.getBusinessId());
                form.setDeptName(ubo.getBusinessName());
            }
        }
//        form.getAnnouncement().setAnnouncementId(21212132L);
        form.getAnnouncement().setBusinessEmail(businessemail);
        form.getAnnouncement().setBusinessFax(businessfax);
        form.getAnnouncement().setBusinessTelephone(businessphone);
        form.getAnnouncement().setManufactureEmail(manufactureemail);
        form.getAnnouncement().setManufactureFax(manufacturefax);
        form.getAnnouncement().setManufactureTel(manufacturephone);
        form.getAnnouncement().setAnnouncementNo(announcenumber);
        form.getAnnouncement().setAssessmentMethod(announcemethod);
        form.getAnnouncement().setMatchingTarget(matchingtarget);
        if (!announcedate.isEmpty()) {
            form.getAnnouncement().setPublishDate(formatter.parse(announcedate.substring(0, 10)));
        }
        form.getAnnouncement().setSigner(announcesignname);

        form.setDetailProduct(new DetailProductForm());
        form.getDetailProduct().setProductNo(productno);
        if (form.getFileType() != null && form.getFileTypeName() != null) {
            form.getDetailProduct().setProductType(form.getProductTypeId());
            form.getDetailProduct().setProductTypeName(form.getProductTypeName());
        }
        //Sua sang lay Id
        CategoryDAOHE cth = new CategoryDAOHE();

        //err
//        Long type = cth.findCategoryByTypeAndCode("SP", producttypecode).getCategoryId();
//        form.getDetailProduct().setProductType(type);
        form.getDetailProduct().setProductSmell(productsmell);
        form.getDetailProduct().setProductStatus(productstatus);
        form.getDetailProduct().setProductColor(productcolor);
        form.getDetailProduct().setProductOtherStatus(productotherstate);
        form.getDetailProduct().setComponents(components);

        form.getDetailProduct().setTimeInUse(timeinuse);
        form.getDetailProduct().setObjectUse(objectusage);
        form.getDetailProduct().setUseage(useage);
        form.getDetailProduct().setGuideline(guideline);
        //form.getDetailProduct().setPreservation();
        form.getDetailProduct().setPackateMaterial(packatematerial);
        form.getDetailProduct().setProductionProcess(productionprocess);
        form.getDetailProduct().setCounterfeitDistinctive(productcompare);
        form.getDetailProduct().setProductTypeName(productname);
        form.getDetailProduct().setOrigin(id);
//        if (impacttargetslist.getIMPACTTARGETDto() != null && impacttargetslist.getIMPACTTARGETDto().size() > 0) {
//            form.getDetailProduct().setOtherTarget(hp.getIMPACTTARGET_NAME(impacttargetslist.getIMPACTTARGETDto()));
//        }
        //thieu product name
        //form.setProductName();
        //hien tai he thong dang de la string k phai danh muc
//        form.setMatchingTarget(MATCHING_TARGET);
        //hien tai he thong dang quan ly theo ten khong theo danh muc
        // mainly target
        List<MainlyTarget> lstMainlyTarget = new ArrayList<MainlyTarget>();
        for (MAINLYTARGETSDtoType bo : mainlytargetslist.mainlytargetsDto) {
            MainlyTarget temp = new MainlyTarget();
            temp.setMeetLevel(bo.getMEETLEVELDES());
            temp.setTargetName(bo.getTARGETNAME());
            temp.setPublishLevel(bo.getPUBLISHLEVEL());
            CategoryDAOHE catedaohe = new CategoryDAOHE();
            Category cate = catedaohe.findCategoryByTypeAndCode("DVI", bo.getUNITCODE());
            if (cate != null && cate.getName().isEmpty() == false) {
                temp.setUnitName(cate.getName());
                temp.setUnitId(cate.getCategoryId().toString());
            }
            lstMainlyTarget.add(temp);
        }
        form.setLstMainlyTarget(lstMainlyTarget);

        //productbiotarget
        List<ProductTarget> lstBioTarget = new ArrayList<ProductTarget>();
        for (BIOTARGETDtoType bo : biotargetlist.biotargetDto) {
            ProductTarget temp = new ProductTarget();
            temp.setMaxLevel(bo.getMAXLEVEL());
            temp.setTargetName(bo.getTARGETNAME());
            CategoryDAOHE catedaohe = new CategoryDAOHE();
            Category cate = catedaohe.findCategoryByTypeAndCode("DVI", bo.getUNITCODE());
            if (cate != null && cate.getName().isEmpty() == false) {
                temp.setUnitName(cate.getName());
                temp.setUnitId(cate.getCategoryId().toString());
            }
            temp.setTargetType(1L);
            lstBioTarget.add(temp);
        }
        form.setLstBioTarget(lstBioTarget);

        // product_physical_chemical
        List<ProductTarget> lstChemical = new ArrayList<ProductTarget>();
        for (CHEMTARGETDtoType bo : unexchemicallist.chemtargetDto) {
            ProductTarget temp = new ProductTarget();
            temp.setMaxLevel(bo.getMAXLEVEL());
            temp.setTargetName(bo.getTARGETNAME());
            CategoryDAOHE catedaohe = new CategoryDAOHE();
            Category cate = catedaohe.findCategoryByTypeAndCode("DVI", bo.getUNITCODE());
            if (cate != null && cate.getName().isEmpty() == false) {
                temp.setUnitName(cate.getName());
                temp.setUnitId(cate.getCategoryId().toString());
            }
            temp.setTargetType(3l);
            lstChemical.add(temp);
        }
        form.setLstChemical(lstChemical);
        //form.setMatchingTarget(null);

        //heavy metal
//        List<ProductTarget> lstHeavyMetal = new ArrayList<ProductTarget>();
//        for (HEAVYTARGETDtoType bo : heavymetallist.heavytargetDto) {
//            ProductTarget temp = new ProductTarget();
//            temp.setMaxLevel(bo.getMAXLEVEL());
//            temp.setTargetName(bo.getTARGETNAME());
//            CategoryDAOHE catedaohe = new CategoryDAOHE();
//            Category cate = catedaohe.findCategoryByTypeAndCode("DVI", bo.getUNITCODE());
//            if (cate != null && cate.getName().isEmpty() == false) {
//                temp.setUnitName(cate.getName());
//                temp.setUnitId(cate.getCategoryId().toString());
//            }
//            temp.setTargetType(2L);
//            lstHeavyMetal.add(temp);
//        }
//        form.setLstHeavyMetal(lstHeavyMetal);
        // attach - pending
//        List<VoAttachs> lstAttachs = new ArrayList<VoAttachs>();
//        for (ATTACHType bo : attachments.attach) {
//            VoAttachs temp = new VoAttachs();
//            temp.setAttachDes(bo.getATTACHDES());
//            temp.setAttachName(bo.getATTACHNAME());
//            lstAttachs.add(temp);
//        }
//        form.setLstAttachs(null);
        //Quality control plan
//        List<QualityControlPlan> lstQualityControl = new ArrayList<QualityControlPlan>();
//        for (CONTROLPLANDtoType bo : qualitycontrolplan.controlplanDto) {
//            QualityControlPlan temp = new QualityControlPlan();
//            temp.setControlTarget(bo.getCONTROLTARGET());
//            temp.setNoteForm(bo.getNOTEFORM());
//            temp.setPatternFrequence(bo.getPATTERNFREQUENCE());
//            temp.setProductProcessDetail(bo.getPRODUCTPROCESSDETAIL());
//            temp.setTechnicalRegulation(bo.getTECHNICALREGULATION());
//            temp.setTestDevice(bo.getTESTDEVICE());
//            temp.setTestMethod(bo.getTESTMETHOD());
//            lstQualityControl.add(temp);
//        }
//        form.setLstQualityControl(lstQualityControl);        
        return form;
    }

    public void validateXML() {
        Validator vd = new Validator();
//
//    public String producttypecode;
//    public String filetypecode;
//    public String statuscode;
//    public String deptcode;
//    public String bussinesscode;
//    public String createdby;
//    public String modifiedby;
//    public String id;
//    public String nswfilecode;
//    public String isdeleted;
//    public String hscode;
//    public MATCHINGTARGETLISTType matchingtargetlist;
//    public MAINLYTARGETSLISTType mainlytargetslist;
//    public BIOTARGETLISTType biotargetlist;
//    public HEAVYMETALLISTType heavymetallist;
//    public UNEXCHEMICALLISTType unexchemicallist;
//    public IMPACTTARGETSLISTType impacttargetslist;
//    public QUALITYCONTROLPLANType qualitycontrolplan;
//    public ATTACHMENTSType attachments;
//    public SignatureType signature;
    }

    public int getObject(Object obj) {
        for (Field field : obj.getClass().getDeclaredFields()) {
            try {
                //field.setAccessible(true); // if you want to modify private fields
                System.out.println(field.getName()
                        + " - " + field.getType()
                        + " - " + field.get(obj));
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(ANNOUNCESENDDtoType.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(ANNOUNCESENDDtoType.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return 0;
    }

    public ANNOUNCESENDDmapFILESFORM botows() {

        return null;
    }
}
