//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 10:52:42 AM ICT 
//


package com.viettel.ws.ANNOUCERECEIVE;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATTACHMENTSDtoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATTACHMENTSDtoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ATTACHMENT_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ATTACHMENT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ATTACHMENT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ATTACH_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FILEBYTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IS_DELETED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FILE_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTACHMENTSDtoType", propOrder = {
    "attachmentid",
    "attachmentcode",
    "attachmentname",
    "attachtypecode",
    "filebyte",
    "isdeleted",
    "filetypecode"
})
public class ATTACHMENTSDtoType {

    @XmlElement(name = "ATTACHMENT_ID")
    public int attachmentid;
    @XmlElement(name = "ATTACHMENT_CODE", required = true)
    public String attachmentcode;
    @XmlElement(name = "ATTACHMENT_NAME", required = true)
    public String attachmentname;
    @XmlElement(name = "ATTACH_TYPE_CODE")
    public int attachtypecode;
    @XmlElement(name = "FILEBYTE", required = true)
    public String filebyte;
    @XmlElement(name = "IS_DELETED")
    public int isdeleted;
    @XmlElement(name = "FILE_TYPE_CODE")
    public int filetypecode;

    /**
     * Gets the value of the attachmentid property.
     * 
     */
    public int getATTACHMENTID() {
        return attachmentid;
    }

    /**
     * Sets the value of the attachmentid property.
     * 
     */
    public void setATTACHMENTID(int value) {
        this.attachmentid = value;
    }

    /**
     * Gets the value of the attachmentcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTACHMENTCODE() {
        return attachmentcode;
    }

    /**
     * Sets the value of the attachmentcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTACHMENTCODE(String value) {
        this.attachmentcode = value;
    }

    /**
     * Gets the value of the attachmentname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTACHMENTNAME() {
        return attachmentname;
    }

    /**
     * Sets the value of the attachmentname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTACHMENTNAME(String value) {
        this.attachmentname = value;
    }

    /**
     * Gets the value of the attachtypecode property.
     * 
     */
    public int getATTACHTYPECODE() {
        return attachtypecode;
    }

    /**
     * Sets the value of the attachtypecode property.
     * 
     */
    public void setATTACHTYPECODE(int value) {
        this.attachtypecode = value;
    }

    /**
     * Gets the value of the filebyte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILEBYTE() {
        return filebyte;
    }

    /**
     * Sets the value of the filebyte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILEBYTE(String value) {
        this.filebyte = value;
    }

    /**
     * Gets the value of the isdeleted property.
     * 
     */
    public int getISDELETED() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     * 
     */
    public void setISDELETED(int value) {
        this.isdeleted = value;
    }

    /**
     * Gets the value of the filetypecode property.
     * 
     */
    public int getFILETYPECODE() {
        return filetypecode;
    }

    /**
     * Sets the value of the filetypecode property.
     * 
     */
    public void setFILETYPECODE(int value) {
        this.filetypecode = value;
    }

}
