//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 10:52:42 AM ICT 
//


package com.viettel.ws.ANNOUCERECEIVE;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATTACHMENTSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATTACHMENTSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ATTACHMENTSDto" type="{}ATTACHMENTSDtoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTACHMENTSType", propOrder = {
    "attachmentsDto"
})
public class ATTACHMENTSType {

    @XmlElement(name = "ATTACHMENTSDto", required = true)
    protected List<ATTACHMENTSDtoType> attachmentsDto;

    /**
     * Gets the value of the attachmentsDto property.
     * 
     * @return
     *     possible object is
     *     {@link ATTACHMENTSDtoType }
     *     
     */
    public List<ATTACHMENTSDtoType> getATTACHMENTSDto() {
        return attachmentsDto;
    }

    /**
     * Sets the value of the attachmentsDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATTACHMENTSDtoType }
     *     
     */
    public void setATTACHMENTSDto(List<ATTACHMENTSDtoType> value) {
        this.attachmentsDto = value;
    }

}
