//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 10:52:42 AM ICT 
//


package com.viettel.ws.ANNOUCERECEIVE;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CONTROLPLANDtoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CONTROLPLANDtoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CONTROL_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CONTROL_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_PROCESS_DETAIL" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CONTROL_TARGET" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TECHNICAL_REGULATION" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PATTERN_FREQUENCE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TEST_DEVICE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TEST_METHOD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NOTE_FORM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NOTE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IS_DELETED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ANNOUNCE_SEND_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CONTROLPLANDtoType", propOrder = {
    "controlid",
    "controlcode",
    "productprocessdetail",
    "controltarget",
    "technicalregulation",
    "patternfrequence",
    "testdevice",
    "testmethod",
    "noteform",
    "note",
    "isdeleted",
    "announcesendid"
})
public class CONTROLPLANDtoType {

    @XmlElement(name = "CONTROL_ID")
    public int controlid;
    @XmlElement(name = "CONTROL_CODE", required = true)
    public String controlcode;
    @XmlElement(name = "PRODUCT_PROCESS_DETAIL")
    public String productprocessdetail;
    @XmlElement(name = "CONTROL_TARGET")
    public String controltarget;
    @XmlElement(name = "TECHNICAL_REGULATION")
    public String technicalregulation;
    @XmlElement(name = "PATTERN_FREQUENCE")
    public String patternfrequence;
    @XmlElement(name = "TEST_DEVICE")
    public String testdevice;
    @XmlElement(name = "TEST_METHOD")
    public String testmethod;
    @XmlElement(name = "NOTE_FORM")
    public String noteform;
    @XmlElement(name = "NOTE")
    public String note;
    @XmlElement(name = "IS_DELETE8")
    public int isdeleted;
    @XmlElement(name = "ANNOUNCE_SEND_ID")
    public int announcesendid;

    /**
     * Gets the value of the controlid property.
     * 
     */
    public int getCONTROLID() {
        return controlid;
    }

    /**
     * Sets the value of the controlid property.
     * 
     */
    public void setCONTROLID(int value) {
        this.controlid = value;
    }

    /**
     * Gets the value of the controlcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTROLCODE() {
        return controlcode;
    }

    /**
     * Sets the value of the controlcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTROLCODE(String value) {
        this.controlcode = value;
    }

    /**
     * Gets the value of the productprocessdetail property.
     * 
     */
    public String getPRODUCTPROCESSDETAIL() {
        return productprocessdetail;
    }

    /**
     * Sets the value of the productprocessdetail property.
     * 
     */
    public void setPRODUCTPROCESSDETAIL(String value) {
        this.productprocessdetail = value;
    }

    /**
     * Gets the value of the controltarget property.
     * 
     */
    public String getCONTROLTARGET() {
        return controltarget;
    }

    /**
     * Sets the value of the controltarget property.
     * 
     */
    public void setCONTROLTARGET(String value) {
        this.controltarget = value;
    }

    /**
     * Gets the value of the technicalregulation property.
     * 
     */
    public String getTECHNICALREGULATION() {
        return technicalregulation;
    }

    /**
     * Sets the value of the technicalregulation property.
     * 
     */
    public void setTECHNICALREGULATION(String value) {
        this.technicalregulation = value;
    }

    /**
     * Gets the value of the patternfrequence property.
     * 
     */
    public String getPATTERNFREQUENCE() {
        return patternfrequence;
    }

    /**
     * Sets the value of the patternfrequence property.
     * 
     */
    public void setPATTERNFREQUENCE(String value) {
        this.patternfrequence = value;
    }

    /**
     * Gets the value of the testdevice property.
     * 
     */
    public String getTESTDEVICE() {
        return testdevice;
    }

    /**
     * Sets the value of the testdevice property.
     * 
     */
    public void setTESTDEVICE(String value) {
        this.testdevice = value;
    }

    /**
     * Gets the value of the testmethod property.
     * 
     */
    public String getTESTMETHOD() {
        return testmethod;
    }

    /**
     * Sets the value of the testmethod property.
     * 
     */
    public void setTESTMETHOD(String value) {
        this.testmethod = value;
    }

    /**
     * Gets the value of the noteform property.
     * 
     */
    public String getNOTEFORM() {
        return noteform;
    }

    /**
     * Sets the value of the noteform property.
     * 
     */
    public void setNOTEFORM(String value) {
        this.noteform = value;
    }

    /**
     * Gets the value of the note property.
     * 
     */
    public String getNOTE() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     */
    public void setNOTE(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the isdeleted property.
     * 
     */
    public int getISDELETED() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     * 
     */
    public void setISDELETED(int value) {
        this.isdeleted = value;
    }

    /**
     * Gets the value of the announcesendid property.
     * 
     */
    public int getANNOUNCESENDID() {
        return announcesendid;
    }

    /**
     * Sets the value of the announcesendid property.
     * 
     */
    public void setANNOUNCESENDID(int value) {
        this.announcesendid = value;
    }

}
