//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 10:52:42 AM ICT 
//


package com.viettel.ws.ANNOUCERECEIVE;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IMPACTTARGETDtoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IMPACTTARGETDtoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IMPACT_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IMPACT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TARGET_NAME" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="UNIT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PUBLISH_LEVEL" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IS_DELETED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ANNOUNCE_SEND_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IMPACTTARGETDtoType", propOrder = {
    "impactid",
    "impactcode",
    "targetname",
    "unitcode",
    "publishlevel",
    "isdeleted",
    "announcesendid"
})
public class IMPACTTARGETDtoType {

    @XmlElement(name = "IMPACT_ID")
    public int impactid;
    @XmlElement(name = "IMPACT_CODE", required = true)
    public String impactcode;
    @XmlElement(name = "TARGET_NAME")
    public String targetname;
    @XmlElement(name = "UNIT_CODE", required = true)
    public String unitcode;
    @XmlElement(name = "PUBLISH_LEVEL")
    public String publishlevel;
    @XmlElement(name = "IS_DELETED")
    public int isdeleted;
    @XmlElement(name = "ANNOUNCE_SEND_ID")
    public int announcesendid;

    /**
     * Gets the value of the impactid property.
     * 
     */
    public int getIMPACTID() {
        return impactid;
    }

    /**
     * Sets the value of the impactid property.
     * 
     */
    public void setIMPACTID(int value) {
        this.impactid = value;
    }

    /**
     * Gets the value of the impactcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPACTCODE() {
        return impactcode;
    }

    /**
     * Sets the value of the impactcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPACTCODE(String value) {
        this.impactcode = value;
    }

    /**
     * Gets the value of the targetname property.
     * 
     */
    public String getTARGETNAME() {
        return targetname;
    }

    /**
     * Sets the value of the targetname property.
     * 
     */
    public void setTARGETNAME(String value) {
        this.targetname = value;
    }

    /**
     * Gets the value of the unitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITCODE() {
        return unitcode;
    }

    /**
     * Sets the value of the unitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITCODE(String value) {
        this.unitcode = value;
    }

    /**
     * Gets the value of the publishlevel property.
     * 
     */
    public String getPUBLISHLEVEL() {
        return publishlevel;
    }

    /**
     * Sets the value of the publishlevel property.
     * 
     */
    public void setPUBLISHLEVEL(String value) {
        this.publishlevel = value;
    }

    /**
     * Gets the value of the isdeleted property.
     * 
     */
    public int getISDELETED() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     * 
     */
    public void setISDELETED(int value) {
        this.isdeleted = value;
    }

    /**
     * Gets the value of the announcesendid property.
     * 
     */
    public int getANNOUNCESENDID() {
        return announcesendid;
    }

    /**
     * Sets the value of the announcesendid property.
     * 
     */
    public void setANNOUNCESENDID(int value) {
        this.announcesendid = value;
    }

}
