//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 10:52:42 AM ICT 
//


package com.viettel.ws.ANNOUCERECEIVE;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MAINLYTARGETSDtoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MAINLYTARGETSDtoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MAINLY_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MAINLY_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TARGET_NAME" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="UNIT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PUBLISH_LEVEL" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IS_DELETED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ANNOUNCE_SEND_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MEET_LEVEL_DES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MAINLYTARGETSDtoType", propOrder = {
    "mainlyid",
    "mainlycode",
    "targetname",
    "unitcode",
    "publishlevel",
    "isdeleted",
    "announcesendid",
    "meetleveldes"
})
public class MAINLYTARGETSDtoType {

    @XmlElement(name = "MAINLY_ID")
    public int mainlyid;
    @XmlElement(name = "MAINLY_CODE", required = true)
    public String mainlycode;
    @XmlElement(name = "TARGET_NAME1")
    public String targetname;
    @XmlElement(name = "UNIT_CODE1", required = true)
    public String unitcode;
    @XmlElement(name = "PUBLISH_LEVEL1")
    public String publishlevel;
    @XmlElement(name = "IS_DELETED3")
    public int isdeleted;
    @XmlElement(name = "ANNOUNCE_SEND_ID")
    public int announcesendid;
    @XmlElement(name = "MEET_LEVEL_DES", required = true)
    public String meetleveldes;

    /**
     * Gets the value of the mainlyid property.
     * 
     */
    public int getMAINLYID() {
        return mainlyid;
    }

    /**
     * Sets the value of the mainlyid property.
     * 
     */
    public void setMAINLYID(int value) {
        this.mainlyid = value;
    }

    /**
     * Gets the value of the mainlycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAINLYCODE() {
        return mainlycode;
    }

    /**
     * Sets the value of the mainlycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAINLYCODE(String value) {
        this.mainlycode = value;
    }

    /**
     * Gets the value of the targetname property.
     * 
     */
    public String getTARGETNAME() {
        return targetname;
    }

    /**
     * Sets the value of the targetname property.
     * 
     */
    public void setTARGETNAME(String value) {
        this.targetname = value;
    }

    /**
     * Gets the value of the unitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITCODE() {
        return unitcode;
    }

    /**
     * Sets the value of the unitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITCODE(String value) {
        this.unitcode = value;
    }

    /**
     * Gets the value of the publishlevel property.
     * 
     */
    public String getPUBLISHLEVEL() {
        return publishlevel;
    }

    /**
     * Sets the value of the publishlevel property.
     * 
     */
    public void setPUBLISHLEVEL(String value) {
        this.publishlevel = value;
    }

    /**
     * Gets the value of the isdeleted property.
     * 
     */
    public int getISDELETED() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     * 
     */
    public void setISDELETED(int value) {
        this.isdeleted = value;
    }

    /**
     * Gets the value of the announcesendid property.
     * 
     */
    public int getANNOUNCESENDID() {
        return announcesendid;
    }

    /**
     * Sets the value of the announcesendid property.
     * 
     */
    public void setANNOUNCESENDID(int value) {
        this.announcesendid = value;
    }

    /**
     * Gets the value of the meetleveldes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEETLEVELDES() {
        return meetleveldes;
    }

    /**
     * Sets the value of the meetleveldes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEETLEVELDES(String value) {
        this.meetleveldes = value;
    }

}
