//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 10:52:42 AM ICT 
//


package com.viettel.ws.ANNOUCERECEIVE;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MATCHINGTARGETDtoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MATCHINGTARGETDtoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MATCHING_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MATCHING_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TARGET_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IS_DELETED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ANNOUNCE_SEND_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MATCHINGTARGETDtoType", propOrder = {
    "matchingid",
    "matchingcode",
    "targetcode",
    "isdeleted",
    "announcesendid"
})
public class MATCHINGTARGETDtoType {

    @XmlElement(name = "MATCHING_ID")
    public int matchingid;
    @XmlElement(name = "MATCHING_CODE", required = true)
    public String matchingcode;
    @XmlElement(name = "TARGET_CODE")
    public String targetcode;
    @XmlElement(name = "IS_DELETED2")
    public int isdeleted;
    @XmlElement(name = "ANNOUNCE_SEND_ID")
    public int announcesendid;

    /**
     * Gets the value of the matchingid property.
     * 
     */
    public int getMATCHINGID() {
        return matchingid;
    }

    /**
     * Sets the value of the matchingid property.
     * 
     */
    public void setMATCHINGID(int value) {
        this.matchingid = value;
    }

    /**
     * Gets the value of the matchingcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATCHINGCODE() {
        return matchingcode;
    }

    /**
     * Sets the value of the matchingcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATCHINGCODE(String value) {
        this.matchingcode = value;
    }

    /**
     * Gets the value of the targetcode property.
     * 
     */
    public String getTARGETCODE() {
        return targetcode;
    }

    /**
     * Sets the value of the targetcode property.
     * 
     */
    public void setTARGETCODE(String value) {
        this.targetcode = value;
    }

    /**
     * Gets the value of the isdeleted property.
     * 
     */
    public int getISDELETED() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     * 
     */
    public void setISDELETED(int value) {
        this.isdeleted = value;
    }

    /**
     * Gets the value of the announcesendid property.
     * 
     */
    public int getANNOUNCESENDID() {
        return announcesendid;
    }

    /**
     * Sets the value of the announcesendid property.
     * 
     */
    public void setANNOUNCESENDID(int value) {
        this.announcesendid = value;
    }

}
