//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 10:52:42 AM ICT 
//


package com.viettel.ws.ANNOUCERECEIVE;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.viettel.ws.ANNOUCERECEIVE package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ANNOUNCESENDDto_QNAME = new QName("", "ANNOUNCESENDDto");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.viettel.ws.ANNOUCERECEIVE
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ANNOUNCESENDDtoType }
     * 
     */
    public ANNOUNCESENDDtoType createANNOUNCESENDDtoType() {
        return new ANNOUNCESENDDtoType();
    }

    /**
     * Create an instance of {@link X509IssuerSerialType }
     * 
     */
    public X509IssuerSerialType createX509IssuerSerialType() {
        return new X509IssuerSerialType();
    }

    /**
     * Create an instance of {@link CONTROLPLANDtoType }
     * 
     */
    public CONTROLPLANDtoType createCONTROLPLANDtoType() {
        return new CONTROLPLANDtoType();
    }

    /**
     * Create an instance of {@link KeyInfoType }
     * 
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    /**
     * Create an instance of {@link IMPACTTARGETDtoType }
     * 
     */
    public IMPACTTARGETDtoType createIMPACTTARGETDtoType() {
        return new IMPACTTARGETDtoType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link QUALITYCONTROLPLANType }
     * 
     */
    public QUALITYCONTROLPLANType createQUALITYCONTROLPLANType() {
        return new QUALITYCONTROLPLANType();
    }

    /**
     * Create an instance of {@link IMPACTTARGETSLISTType }
     * 
     */
    public IMPACTTARGETSLISTType createIMPACTTARGETSLISTType() {
        return new IMPACTTARGETSLISTType();
    }

    /**
     * Create an instance of {@link MAINLYTARGETSDtoType }
     * 
     */
    public MAINLYTARGETSDtoType createMAINLYTARGETSDtoType() {
        return new MAINLYTARGETSDtoType();
    }

    /**
     * Create an instance of {@link ATTACHMENTSDtoType }
     * 
     */
    public ATTACHMENTSDtoType createATTACHMENTSDtoType() {
        return new ATTACHMENTSDtoType();
    }

    /**
     * Create an instance of {@link MAINLYTARGETSLISTType }
     * 
     */
    public MAINLYTARGETSLISTType createMAINLYTARGETSLISTType() {
        return new MAINLYTARGETSLISTType();
    }

    /**
     * Create an instance of {@link DigestMethodType }
     * 
     */
    public DigestMethodType createDigestMethodType() {
        return new DigestMethodType();
    }

    /**
     * Create an instance of {@link HEAVYMETALLISTType }
     * 
     */
    public HEAVYMETALLISTType createHEAVYMETALLISTType() {
        return new HEAVYMETALLISTType();
    }

    /**
     * Create an instance of {@link UNEXCHEMICALLISTType }
     * 
     */
    public UNEXCHEMICALLISTType createUNEXCHEMICALLISTType() {
        return new UNEXCHEMICALLISTType();
    }

    /**
     * Create an instance of {@link CHEMTARGETDtoType }
     * 
     */
    public CHEMTARGETDtoType createCHEMTARGETDtoType() {
        return new CHEMTARGETDtoType();
    }

    /**
     * Create an instance of {@link ATTACHMENTSType }
     * 
     */
    public ATTACHMENTSType createATTACHMENTSType() {
        return new ATTACHMENTSType();
    }

    /**
     * Create an instance of {@link HEAVYTARGETDtoType }
     * 
     */
    public HEAVYTARGETDtoType createHEAVYTARGETDtoType() {
        return new HEAVYTARGETDtoType();
    }

    /**
     * Create an instance of {@link CanonicalizationMethodType }
     * 
     */
    public CanonicalizationMethodType createCanonicalizationMethodType() {
        return new CanonicalizationMethodType();
    }

    /**
     * Create an instance of {@link SignedInfoType }
     * 
     */
    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    /**
     * Create an instance of {@link TransformsType }
     * 
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link BIOTARGETLISTType }
     * 
     */
    public BIOTARGETLISTType createBIOTARGETLISTType() {
        return new BIOTARGETLISTType();
    }

    /**
     * Create an instance of {@link MATCHINGTARGETDtoType }
     * 
     */
    public MATCHINGTARGETDtoType createMATCHINGTARGETDtoType() {
        return new MATCHINGTARGETDtoType();
    }

    /**
     * Create an instance of {@link MATCHINGTARGETLISTType }
     * 
     */
    public MATCHINGTARGETLISTType createMATCHINGTARGETLISTType() {
        return new MATCHINGTARGETLISTType();
    }

    /**
     * Create an instance of {@link TransformType }
     * 
     */
    public TransformType createTransformType() {
        return new TransformType();
    }

    /**
     * Create an instance of {@link X509DataType }
     * 
     */
    public X509DataType createX509DataType() {
        return new X509DataType();
    }

    /**
     * Create an instance of {@link BIOTARGETDtoType }
     * 
     */
    public BIOTARGETDtoType createBIOTARGETDtoType() {
        return new BIOTARGETDtoType();
    }

    /**
     * Create an instance of {@link SignatureMethodType }
     * 
     */
    public SignatureMethodType createSignatureMethodType() {
        return new SignatureMethodType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ANNOUNCESENDDtoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ANNOUNCESENDDto")
    public JAXBElement<ANNOUNCESENDDtoType> createANNOUNCESENDDto(ANNOUNCESENDDtoType value) {
        return new JAXBElement<ANNOUNCESENDDtoType>(_ANNOUNCESENDDto_QNAME, ANNOUNCESENDDtoType.class, null, value);
    }

}
