//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.14 at 04:48:10 PM ICT 
package com.viettel.ws.BO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ANNOUNCERESULTDto complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ANNOUNCERESULTDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AUTHENTICATE" type="{}AUTHENTICATE"/>
 *         &lt;element name="NSW_FILE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DEPT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SIGNER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SIGN_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COMMENTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RESULTPAGER" type="{}RESULTPAGER"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name = "ANNOUNCERESULT")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ANNOUNCERESULTDto", propOrder = {
    "authenticate",
    "nswfilecode",
    "statuscode",
    "deptcode",
    "signername",
    "signdate",
    "comments",
    "resultpager"
})
public class ANNOUNCERESULTDto {

    @XmlElement(name = "AUTHENTICATE", required = true)
    protected AUTHENTICATE authenticate;
    @XmlElement(name = "NSW_FILE_CODE", required = true)
    protected String nswfilecode;
    @XmlElement(name = "STATUS_CODE", required = true)
    protected String statuscode;
    @XmlElement(name = "DEPT_CODE", required = true)
    protected String deptcode;
    @XmlElement(name = "SIGNER_NAME", required = true)
    protected String signername;
    @XmlElement(name = "SIGN_DATE", required = true)
    protected String signdate;
    @XmlElement(name = "COMMENTS", required = true)
    protected String comments;
    @XmlElement(name = "RESULTPAGER", required = true)
    protected RESULTPAGER resultpager;

    /**
     * Gets the value of the authenticate property.
     *
     * @return possible object is {@link AUTHENTICATE }
     *
     */
    public AUTHENTICATE getAUTHENTICATE() {
        return authenticate;
    }

    /**
     * Sets the value of the authenticate property.
     *
     * @param value allowed object is {@link AUTHENTICATE }
     *
     */
    public void setAUTHENTICATE(AUTHENTICATE value) {
        this.authenticate = value;
    }

    /**
     * Gets the value of the nswfilecode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNSWFILECODE() {
        return nswfilecode;
    }

    /**
     * Sets the value of the nswfilecode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNSWFILECODE(String value) {
        this.nswfilecode = value;
    }

    /**
     * Gets the value of the statuscode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSTATUSCODE() {
        return statuscode;
    }

    /**
     * Sets the value of the statuscode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSTATUSCODE(String value) {
        this.statuscode = value;
    }

    /**
     * Gets the value of the deptcode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDEPTCODE() {
        return deptcode;
    }

    /**
     * Sets the value of the deptcode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDEPTCODE(String value) {
        this.deptcode = value;
    }

    /**
     * Gets the value of the signername property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSIGNERNAME() {
        return signername;
    }

    /**
     * Sets the value of the signername property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSIGNERNAME(String value) {
        this.signername = value;
    }

    /**
     * Gets the value of the signdate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSIGNDATE() {
        return signdate;
    }

    /**
     * Sets the value of the signdate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSIGNDATE(String value) {
        this.signdate = value;
    }

    /**
     * Gets the value of the comments property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCOMMENTS() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCOMMENTS(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the resultpager property.
     *
     * @return possible object is {@link RESULTPAGER }
     *
     */
    public RESULTPAGER getRESULTPAGER() {
        return resultpager;
    }

    /**
     * Sets the value of the resultpager property.
     *
     * @param value allowed object is {@link RESULTPAGER }
     *
     */
    public void setRESULTPAGER(RESULTPAGER value) {
        this.resultpager = value;
    }

    public ANNOUNCERESULTDto(AUTHENTICATE authenticate, String nswfilecode, String statuscode, String deptcode, String signername, String signdate, String comments, RESULTPAGER resultpager) {
        this.authenticate = authenticate;
        this.nswfilecode = nswfilecode;
        this.statuscode = statuscode;
        this.deptcode = deptcode;
        this.signername = signername;
        this.signdate = signdate;
        this.comments = comments;
        this.resultpager = resultpager;
    }

    public ANNOUNCERESULTDto() {
    }

}
