//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.24 at 11:29:34 AM ICT 
//


package com.viettel.ws.BO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Attachment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Attachment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AttacmentCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttacmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttachmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Base64FileContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Attachment", propOrder = {
    "attachmentId",
    "attachmentCode",
    "attachmentTypeCode",
    "attachmentName",
    "base64FileContent"
})
public class Attachment {

    @XmlElement(name = "AttachmentId")
    protected String attachmentId;
    @XmlElement(name = "AttachmentCode", required = true)
    protected String attachmentCode;
    @XmlElement(name = "AttachmentTypeCode", required = true)
    protected String attachmentTypeCode;
    @XmlElement(name = "AttachmentName", required = true)
    protected String attachmentName;
    @XmlElement(name = "Base64FileContent", required = true)
    protected String base64FileContent;

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

   
    
    /**
     * Gets the value of the attacmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachmentCode() {
        return attachmentCode;
    }

    /**
     * Sets the value of the attacmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachmentCode(String value) {
        this.attachmentCode = value;
    }

    /**
     * Gets the value of the attacmentTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachmentTypeCode() {
        return attachmentTypeCode;
    }

    /**
     * Sets the value of the attacmentTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachmentTypeCode(String value) {
        this.attachmentTypeCode = value;
    }

    /**
     * Gets the value of the attachmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * Sets the value of the attachmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachmentName(String value) {
        this.attachmentName = value;
    }

    /**
     * Gets the value of the base64FileContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase64FileContent() {
        return base64FileContent;
    }

    /**
     * Sets the value of the base64FileContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase64FileContent(String value) {
        this.base64FileContent = value;
    }

}
