//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.24 at 11:29:34 AM ICT 
//
package com.viettel.ws.BO;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Content complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Content">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfilePublishedCosmetics" type="{}ProfilePublishedCosmetics"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "Content", propOrder = {
// "profilePublishedCosmetics"
// })
@XmlType(name = "Content")
public class Content {

    public Content() {
    }

//    public Content(ProfilePublishedCosmetics profilePublishedCosmetics, String ReceiveDate, List<Error> ErrorList) {
//        this.profilePublishedCosmetics = profilePublishedCosmetics;
//        this.ReceiveDate = ReceiveDate;
//        this.ErrorList = ErrorList;
//    }
    @XmlElement(name = "ProfilePublishedCosmetics")
    protected ProfilePublishedCosmetics profilePublishedCosmetics;
    @XmlElement(name = "ReceiveDate")
    private String ReceiveDate;
//    @XmlElementWrapper(name = "ErrorList")
//    @XmlElement(name = "Error")
//    private List<Error> ErrorList;
    @XmlElement(name = "RejectDate")
    private String RejectDate;
    //linhdx
    @XmlElement(name = "Attachment")
    private Attachment Attachment;
    @XmlElement(name = "AcceptRequestProductNotification")
    private AcceptRequestProductNotification AcceptRequestProductNotification;

    /**
     * Gets the value of the profilePublishedCosmetics property.
     *
     * @return possible object is {@link ProfilePublishedCosmetics }
     *
     */
    public ProfilePublishedCosmetics getProfilePublishedCosmetics() {
        return profilePublishedCosmetics;
    }

    /**
     * Sets the value of the profilePublishedCosmetics property.
     *
     * @param value allowed object is {@link ProfilePublishedCosmetics }
     *
     */
    public void setProfilePublishedCosmetics(ProfilePublishedCosmetics value) {
        this.profilePublishedCosmetics = value;
    }

//    public List<Error> getErrorList() {
//        return ErrorList;
//    }
//
//    public void setErrorList(List<Error> ErrorList) {
//        this.ErrorList = ErrorList;
//    }

    public String getReceiveDate() {
        return ReceiveDate;
    }

    public void setReceiveDate(String ReceiveDate) {
        this.ReceiveDate = ReceiveDate;
    }

   
    public String getRejectDate() {
        return RejectDate;
    }

    public void setRejectDate(String RejectDate) {
        this.RejectDate = RejectDate;
    }

    public Attachment getAttachment() {
        return Attachment;
    }

    public void setAttachment(Attachment Attachment) {
        this.Attachment = Attachment;
    }

    public AcceptRequestProductNotification getAcceptRequestProductNotification() {
        return AcceptRequestProductNotification;
    }

    public void setAcceptRequestProductNotification(AcceptRequestProductNotification AcceptRequestProductNotification) {
        this.AcceptRequestProductNotification = AcceptRequestProductNotification;
    }
    
}
