//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 04:37:11 PM ICT 
//


package com.viettel.ws.BO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import jxl.write.DateTime;

/**
 * <p>Java class for IMPORT_RESULT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IMPORT_RESULT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IMPORTER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMPORTER_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMPORTER_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMPORTER_FAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMPORTER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPORTER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPORTER_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPORTER_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPORTER_FAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPORTER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CONTRACT_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRANS_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRANS_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMPORTER_IMPORT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMPORTER_IMPORT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPORTER_IMPORT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT" type="{}PRODUCT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IMPORT_RESULT", propOrder = {
    "importername",
    "importeraddress",
    "importerphone",
    "importerfax",
    "importeremail",
    "exportername",
    "exporteraddress",
    "exporterphone",
    "exporterfax",
    "exporteremail",
    "contractno",
    "transno",
    "transdate",
    "importerimportcode",
    "importerimportname",
    "exporterimportname",
    "product"
})
public class IMPORTRESULT {

    @XmlElement(name = "IMPORTER_NAME", required = true)
    protected String importername;
    @XmlElement(name = "IMPORTER_ADDRESS", required = true)
    protected String importeraddress;
    @XmlElement(name = "IMPORTER_PHONE", required = true)
    protected String importerphone;
    @XmlElement(name = "IMPORTER_FAX", required = true)
    protected String importerfax;
    @XmlElement(name = "IMPORTER_EMAIL", required = true)
    protected String importeremail;
    @XmlElement(name = "EXPORTER_NAME", required = true)
    protected String exportername;
    @XmlElement(name = "EXPORTER_ADDRESS", required = true)
    protected String exporteraddress;
    @XmlElement(name = "EXPORTER_PHONE", required = true)
    protected String exporterphone;
    @XmlElement(name = "EXPORTER_FAX", required = true)
    protected String exporterfax;
    @XmlElement(name = "EXPORTER_EMAIL", required = true)
    protected String exporteremail;
    @XmlElement(name = "CONTRACT_NO", required = true)
    protected String contractno;
    @XmlElement(name = "TRANS_NO", required = true)
    protected String transno;
    @XmlElement(name = "TRANS_DATE", required = true)
    protected String transdate;
    @XmlElement(name = "_IMPORTER_GATE_CODE", required = true)
    protected String importergatecode;
    @XmlElement(name = "_IMPORTER_GATE_NAME", required = true)
    protected String importergatename;
    @XmlElement(name = "EXPORTER_GATE_NAME", required = true)
    protected String exportergatename;
    
    @XmlElement(name = "COMMENTS", required = true)
    protected String comments;
    @XmlElement(name = "LICENSE_NO", required = true)
    protected String licenseno;
    @XmlElement(name = "DATE_OF_ISSUE", required = true)
    protected DateTime dateofissue;
    @XmlElement(name = "EXPIRED_DATE_OF_ISSUE", required = true)
    protected DateTime expireddateofissue;
    @XmlElement(name = "PROCESS_PLACE", required = true)
    protected String processplace;
    @XmlElement(name = "EXPORTER_GATE_CODE", required = true)
    protected String exportergatecode;
    
    @XmlElement(name = "PRODUCT", required = true)
    protected PRODUCT product;

    /**
     * Gets the value of the importername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTERNAME() {
        return importername;
    }

    /**
     * Sets the value of the importername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTERNAME(String value) {
        this.importername = value;
    }

    /**
     * Gets the value of the importeraddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTERADDRESS() {
        return importeraddress;
    }

    /**
     * Sets the value of the importeraddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTERADDRESS(String value) {
        this.importeraddress = value;
    }

    /**
     * Gets the value of the importerphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTERPHONE() {
        return importerphone;
    }

    /**
     * Sets the value of the importerphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTERPHONE(String value) {
        this.importerphone = value;
    }

    /**
     * Gets the value of the importerfax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTERFAX() {
        return importerfax;
    }

    /**
     * Sets the value of the importerfax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTERFAX(String value) {
        this.importerfax = value;
    }

    /**
     * Gets the value of the importeremail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTEREMAIL() {
        return importeremail;
    }

    /**
     * Sets the value of the importeremail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTEREMAIL(String value) {
        this.importeremail = value;
    }

    /**
     * Gets the value of the exportername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPORTERNAME() {
        return exportername;
    }

    /**
     * Sets the value of the exportername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPORTERNAME(String value) {
        this.exportername = value;
    }

    /**
     * Gets the value of the exporteraddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPORTERADDRESS() {
        return exporteraddress;
    }

    /**
     * Sets the value of the exporteraddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPORTERADDRESS(String value) {
        this.exporteraddress = value;
    }

    /**
     * Gets the value of the exporterphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPORTERPHONE() {
        return exporterphone;
    }

    /**
     * Sets the value of the exporterphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPORTERPHONE(String value) {
        this.exporterphone = value;
    }

    /**
     * Gets the value of the exporterfax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPORTERFAX() {
        return exporterfax;
    }

    /**
     * Sets the value of the exporterfax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPORTERFAX(String value) {
        this.exporterfax = value;
    }

    /**
     * Gets the value of the exporteremail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPORTEREMAIL() {
        return exporteremail;
    }

    /**
     * Sets the value of the exporteremail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPORTEREMAIL(String value) {
        this.exporteremail = value;
    }

    /**
     * Gets the value of the contractno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTNO() {
        return contractno;
    }

    /**
     * Sets the value of the contractno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTNO(String value) {
        this.contractno = value;
    }

    /**
     * Gets the value of the transno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSNO() {
        return transno;
    }

    /**
     * Sets the value of the transno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSNO(String value) {
        this.transno = value;
    }

    /**
     * Gets the value of the transdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSDATE() {
        return transdate;
    }

    /**
     * Sets the value of the transdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSDATE(String value) {
        this.transdate = value;
    }

    /**
     * Gets the value of the importerimportcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTERGATECODE() {
        return importergatecode;
    }

    /**
     * Sets the value of the importerimportcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTERGATECODE(String value) {
        this.importergatecode = value;
    }

    /**
     * Gets the value of the importerimportname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTERGATENAME() {
        return importergatename;
    }

    /**
     * Sets the value of the importerimportname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTERGATENAME(String value) {
        this.importergatename = value;
    }

    /**
     * Gets the value of the exporterimportname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPORTERGATENAME() {
        return exportergatename;
    }

    /**
     * Sets the value of the exporterimportname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPORTERGATENAME(String value) {
        this.exportergatename = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCT }
     *     
     */
    public PRODUCT getPRODUCT() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCT }
     *     
     */
    public void setPRODUCT(PRODUCT value) {
        this.product = value;
    }

    public IMPORTRESULT(String importername, String importeraddress, String importerphone, String importerfax, String importeremail, String exportername, String exporteraddress, String exporterphone, String exporterfax, String exporteremail, String contractno, String transno, String transdate, String importergatecode, String importergatename, String exportergatename, String comments, String licenseno, DateTime dateofissue, DateTime expireddateofissue, String processplace, String exportergatecode, PRODUCT product) {
        this.importername = importername;
        this.importeraddress = importeraddress;
        this.importerphone = importerphone;
        this.importerfax = importerfax;
        this.importeremail = importeremail;
        this.exportername = exportername;
        this.exporteraddress = exporteraddress;
        this.exporterphone = exporterphone;
        this.exporterfax = exporterfax;
        this.exporteremail = exporteremail;
        this.contractno = contractno;
        this.transno = transno;
        this.transdate = transdate;
        this.importergatecode = importergatecode;
        this.importergatename = importergatename;
        this.exportergatename = exportergatename;
        this.comments = comments;
        this.licenseno = licenseno;
        this.dateofissue = dateofissue;
        this.expireddateofissue = expireddateofissue;
        this.processplace = processplace;
        this.exportergatecode = exportergatecode;
        this.product = product;
    }

    public IMPORTRESULT() {
    }

    public String getImportername() {
        return importername;
    }

    public void setImportername(String importername) {
        this.importername = importername;
    }

    public String getImporteraddress() {
        return importeraddress;
    }

    public void setImporteraddress(String importeraddress) {
        this.importeraddress = importeraddress;
    }

    public String getImporterphone() {
        return importerphone;
    }

    public void setImporterphone(String importerphone) {
        this.importerphone = importerphone;
    }

    public String getImporterfax() {
        return importerfax;
    }

    public void setImporterfax(String importerfax) {
        this.importerfax = importerfax;
    }

    public String getImporteremail() {
        return importeremail;
    }

    public void setImporteremail(String importeremail) {
        this.importeremail = importeremail;
    }

    public String getExportername() {
        return exportername;
    }

    public void setExportername(String exportername) {
        this.exportername = exportername;
    }

    public String getExporteraddress() {
        return exporteraddress;
    }

    public void setExporteraddress(String exporteraddress) {
        this.exporteraddress = exporteraddress;
    }

    public String getExporterphone() {
        return exporterphone;
    }

    public void setExporterphone(String exporterphone) {
        this.exporterphone = exporterphone;
    }

    public String getExporterfax() {
        return exporterfax;
    }

    public void setExporterfax(String exporterfax) {
        this.exporterfax = exporterfax;
    }

    public String getExporteremail() {
        return exporteremail;
    }

    public void setExporteremail(String exporteremail) {
        this.exporteremail = exporteremail;
    }

    public String getContractno() {
        return contractno;
    }

    public void setContractno(String contractno) {
        this.contractno = contractno;
    }

    public String getTransno() {
        return transno;
    }

    public void setTransno(String transno) {
        this.transno = transno;
    }

    public String getTransdate() {
        return transdate;
    }

    public void setTransdate(String transdate) {
        this.transdate = transdate;
    }

    public String getImportergatecode() {
        return importergatecode;
    }

    public void setImportergatecode(String importergatecode) {
        this.importergatecode = importergatecode;
    }

    public String getImportergatename() {
        return importergatename;
    }

    public void setImportergatename(String importergatename) {
        this.importergatename = importergatename;
    }

    public String getExportergatename() {
        return exportergatename;
    }

    public void setExportergatename(String exportergatename) {
        this.exportergatename = exportergatename;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getLicenseno() {
        return licenseno;
    }

    public void setLicenseno(String licenseno) {
        this.licenseno = licenseno;
    }

    public DateTime getDateofissue() {
        return dateofissue;
    }

    public void setDateofissue(DateTime dateofissue) {
        this.dateofissue = dateofissue;
    }

    public DateTime getExpireddateofissue() {
        return expireddateofissue;
    }

    public void setExpireddateofissue(DateTime expireddateofissue) {
        this.expireddateofissue = expireddateofissue;
    }

    public String getProcessplace() {
        return processplace;
    }

    public void setProcessplace(String processplace) {
        this.processplace = processplace;
    }

    public String getExportergatecode() {
        return exportergatecode;
    }

    public void setExportergatecode(String exportergatecode) {
        this.exportergatecode = exportergatecode;
    }

    public PRODUCT getProduct() {
        return product;
    }

    public void setProduct(PRODUCT product) {
        this.product = product;
    }

}
