//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 04:37:11 PM ICT 
//


package com.viettel.ws.BO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRODUCTRESULTSDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRODUCTRESULTSDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PRODUCT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_DESCRIPTIONS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NATIONAL_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TOTAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TOTAL_UNIT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NETWEIGHT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NETWEIGHT_UNIT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CONFIRM_ANNOUNCE_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CONFIRM_ANNOUNCE_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="STORE_PLACE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CHECK_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CHECK_TIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="APPRAISAL_INDEPEND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CHECK_METHOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BASE_UNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CURRENCY_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VOLUME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VOLUME_UNIT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PACKAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CREATED_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPIRED_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IMPORT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CONCLUSION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REASONS_REJECT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="METHOD_CHECK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RECEIVED_PLACE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LICENSE_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PROVINCE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DATE_OF_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EXPIRED_DATE_OF_ISSUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRODUCTRESULTSDto", propOrder = {
    "productcode",
    "productdescriptions",
    "producttypecode",
    "productname",
    "nationalcode",
    "total",
    "totalunitcode",
    "netweight",
    "netweightunitcode",
    "confirmannounceno",
    "confirmannouncedate",
    "storeplace",
    "checkaddress",
    "checktime",
    "appraisalindepend",
    "checkmethod",
    "baseunit",
    "currencycode",
    "volume",
    "volumeunitcode",
    "_package",
    "createddate",
    "expireddate",
    "importtype",
    "conclusion",
    "reasonsreject",
    "methodcheck",
    "receivedplace",
    "licenseno",
    "provincecode",
    "dateofissue",
    "expireddateofissue"
})
public class PRODUCTRESULTSDto {

    @XmlElement(name = "PRODUCT_CODE", required = true)
    protected String productcode;
    @XmlElement(name = "PRODUCT_DESCRIPTIONS", required = true)
    protected String productdescriptions;
    @XmlElement(name = "PRODUCT_TYPE_CODE", required = true)
    protected String producttypecode;
    @XmlElement(name = "PRODUCT_NAME", required = true)
    protected String productname;
    @XmlElement(name = "NATIONAL_CODE", required = true)
    protected String nationalcode;
    @XmlElement(name = "TOTAL", required = true)
    protected String total;
    @XmlElement(name = "TOTAL_UNIT_CODE", required = true)
    protected String totalunitcode;
    @XmlElement(name = "NETWEIGHT", required = true)
    protected String netweight;
    @XmlElement(name = "NETWEIGHT_UNIT_CODE", required = true)
    protected String netweightunitcode;
    @XmlElement(name = "CONFIRM_ANNOUNCE_NO", required = true)
    protected String confirmannounceno;
    @XmlElement(name = "CONFIRM_ANNOUNCE_DATE", required = true)
    protected String confirmannouncedate;
    @XmlElement(name = "STORE_PLACE", required = true)
    protected String storeplace;
    @XmlElement(name = "CHECK_ADDRESS", required = true)
    protected String checkaddress;
    @XmlElement(name = "CHECK_TIME", required = true)
    protected String checktime;
    @XmlElement(name = "APPRAISAL_INDEPEND", required = true)
    protected String appraisalindepend;
    @XmlElement(name = "CHECK_METHOD", required = true)
    protected String checkmethod;
    @XmlElement(name = "BASE_UNIT", required = true)
    protected String baseunit;
    @XmlElement(name = "CURRENCY_CODE", required = true)
    protected String currencycode;
    @XmlElement(name = "VOLUME", required = true)
    protected String volume;
    @XmlElement(name = "VOLUME_UNIT_CODE", required = true)
    protected String volumeunitcode;
    @XmlElement(name = "PACKAGE", required = true)
    protected String _package;
    @XmlElement(name = "CREATED_DATE", required = true)
    protected String createddate;
    @XmlElement(name = "EXPIRED_DATE", required = true)
    protected String expireddate;
    @XmlElement(name = "IMPORT_TYPE", required = true)
    protected String importtype;
    @XmlElement(name = "CONCLUSION", required = true)
    protected String conclusion;
    @XmlElement(name = "REASONS_REJECT", required = true)
    protected String reasonsreject;
    @XmlElement(name = "METHOD_CHECK", required = true)
    protected String methodcheck;
    @XmlElement(name = "RECEIVED_PLACE", required = true)
    protected String receivedplace;
    @XmlElement(name = "LICENSE_NO", required = true)
    protected String licenseno;
    @XmlElement(name = "PROVINCE_CODE", required = true)
    protected String provincecode;
    @XmlElement(name = "DATE_OF_ISSUE", required = true)
    protected String dateofissue;
    @XmlElement(name = "EXPIRED_DATE_OF_ISSUE", required = true)
    protected String expireddateofissue;

    /**
     * Gets the value of the productcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTCODE() {
        return productcode;
    }

    /**
     * Sets the value of the productcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTCODE(String value) {
        this.productcode = value;
    }

    /**
     * Gets the value of the productdescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTDESCRIPTIONS() {
        return productdescriptions;
    }

    /**
     * Sets the value of the productdescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTDESCRIPTIONS(String value) {
        this.productdescriptions = value;
    }

    /**
     * Gets the value of the producttypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTTYPECODE() {
        return producttypecode;
    }

    /**
     * Sets the value of the producttypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTTYPECODE(String value) {
        this.producttypecode = value;
    }

    /**
     * Gets the value of the productname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTNAME() {
        return productname;
    }

    /**
     * Sets the value of the productname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTNAME(String value) {
        this.productname = value;
    }

    /**
     * Gets the value of the nationalcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONALCODE() {
        return nationalcode;
    }

    /**
     * Sets the value of the nationalcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONALCODE(String value) {
        this.nationalcode = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTAL() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTAL(String value) {
        this.total = value;
    }

    /**
     * Gets the value of the totalunitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALUNITCODE() {
        return totalunitcode;
    }

    /**
     * Sets the value of the totalunitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALUNITCODE(String value) {
        this.totalunitcode = value;
    }

    /**
     * Gets the value of the netweight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETWEIGHT() {
        return netweight;
    }

    /**
     * Sets the value of the netweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETWEIGHT(String value) {
        this.netweight = value;
    }

    /**
     * Gets the value of the netweightunitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETWEIGHTUNITCODE() {
        return netweightunitcode;
    }

    /**
     * Sets the value of the netweightunitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETWEIGHTUNITCODE(String value) {
        this.netweightunitcode = value;
    }

    /**
     * Gets the value of the confirmannounceno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIRMANNOUNCENO() {
        return confirmannounceno;
    }

    /**
     * Sets the value of the confirmannounceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIRMANNOUNCENO(String value) {
        this.confirmannounceno = value;
    }

    /**
     * Gets the value of the confirmannouncedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIRMANNOUNCEDATE() {
        return confirmannouncedate;
    }

    /**
     * Sets the value of the confirmannouncedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIRMANNOUNCEDATE(String value) {
        this.confirmannouncedate = value;
    }

    /**
     * Gets the value of the storeplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTOREPLACE() {
        return storeplace;
    }

    /**
     * Sets the value of the storeplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTOREPLACE(String value) {
        this.storeplace = value;
    }

    /**
     * Gets the value of the checkaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECKADDRESS() {
        return checkaddress;
    }

    /**
     * Sets the value of the checkaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECKADDRESS(String value) {
        this.checkaddress = value;
    }

    /**
     * Gets the value of the checktime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECKTIME() {
        return checktime;
    }

    /**
     * Sets the value of the checktime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECKTIME(String value) {
        this.checktime = value;
    }

    /**
     * Gets the value of the appraisalindepend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPRAISALINDEPEND() {
        return appraisalindepend;
    }

    /**
     * Sets the value of the appraisalindepend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPRAISALINDEPEND(String value) {
        this.appraisalindepend = value;
    }

    /**
     * Gets the value of the checkmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECKMETHOD() {
        return checkmethod;
    }

    /**
     * Sets the value of the checkmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECKMETHOD(String value) {
        this.checkmethod = value;
    }

    /**
     * Gets the value of the baseunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBASEUNIT() {
        return baseunit;
    }

    /**
     * Sets the value of the baseunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBASEUNIT(String value) {
        this.baseunit = value;
    }

    /**
     * Gets the value of the currencycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRENCYCODE() {
        return currencycode;
    }

    /**
     * Sets the value of the currencycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRENCYCODE(String value) {
        this.currencycode = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVOLUME() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVOLUME(String value) {
        this.volume = value;
    }

    /**
     * Gets the value of the volumeunitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVOLUMEUNITCODE() {
        return volumeunitcode;
    }

    /**
     * Sets the value of the volumeunitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVOLUMEUNITCODE(String value) {
        this.volumeunitcode = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACKAGE() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACKAGE(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the createddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDDATE() {
        return createddate;
    }

    /**
     * Sets the value of the createddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDDATE(String value) {
        this.createddate = value;
    }

    /**
     * Gets the value of the expireddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPIREDDATE() {
        return expireddate;
    }

    /**
     * Sets the value of the expireddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPIREDDATE(String value) {
        this.expireddate = value;
    }

    /**
     * Gets the value of the importtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTTYPE() {
        return importtype;
    }

    /**
     * Sets the value of the importtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTTYPE(String value) {
        this.importtype = value;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONCLUSION() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONCLUSION(String value) {
        this.conclusion = value;
    }

    /**
     * Gets the value of the reasonsreject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREASONSREJECT() {
        return reasonsreject;
    }

    /**
     * Sets the value of the reasonsreject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREASONSREJECT(String value) {
        this.reasonsreject = value;
    }

    /**
     * Gets the value of the methodcheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMETHODCHECK() {
        return methodcheck;
    }

    /**
     * Sets the value of the methodcheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMETHODCHECK(String value) {
        this.methodcheck = value;
    }

    /**
     * Gets the value of the receivedplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIVEDPLACE() {
        return receivedplace;
    }

    /**
     * Sets the value of the receivedplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIVEDPLACE(String value) {
        this.receivedplace = value;
    }

    /**
     * Gets the value of the licenseno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLICENSENO() {
        return licenseno;
    }

    /**
     * Sets the value of the licenseno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLICENSENO(String value) {
        this.licenseno = value;
    }

    /**
     * Gets the value of the provincecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROVINCECODE() {
        return provincecode;
    }

    /**
     * Sets the value of the provincecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROVINCECODE(String value) {
        this.provincecode = value;
    }

    /**
     * Gets the value of the dateofissue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATEOFISSUE() {
        return dateofissue;
    }

    /**
     * Sets the value of the dateofissue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATEOFISSUE(String value) {
        this.dateofissue = value;
    }

    /**
     * Gets the value of the expireddateofissue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPIREDDATEOFISSUE() {
        return expireddateofissue;
    }

    /**
     * Sets the value of the expireddateofissue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPIREDDATEOFISSUE(String value) {
        this.expireddateofissue = value;
    }

}
