//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.14 at 04:48:10 PM ICT 
//


package com.viettel.ws.BO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RESULTPAGER complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RESULTPAGER">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RECEIPT_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PROVINCE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RECEIPT_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RECEIPT_DEPT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSSINESS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_FAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BUSINESS_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HS_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRODUCT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MANUFACTURE_ADD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NATION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REGION_FROM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EFFECTIVE_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RESULTPAGER", propOrder = {
    "receiptno",
    "provincecode",
    "receiptdate",
    "receiptdeptname",
    "bussinesscode",
    "businessname",
    "businessaddress",
    "businessphone",
    "businessfax",
    "businessemail",
    "hscode",
    "producttypecode",
    "productname",
    "manufacturename",
    "manufactureadd",
    "nationcode",
    "regionfrom",
    "effectivedate"
})
public class RESULTPAGER {

    @XmlElement(name = "RECEIPT_NO", required = true)
    protected String receiptno;
    @XmlElement(name = "PROVINCE_CODE", required = true)
    protected String provincecode;
    @XmlElement(name = "RECEIPT_DATE", required = true)
    protected String receiptdate;
    @XmlElement(name = "RECEIPT_DEPT_NAME", required = true)
    protected String receiptdeptname;
    @XmlElement(name = "BUSSINESS_CODE", required = true)
    protected String bussinesscode;
    @XmlElement(name = "BUSINESS_NAME", required = true)
    protected String businessname;
    @XmlElement(name = "BUSINESS_ADDRESS", required = true)
    protected String businessaddress;
    @XmlElement(name = "BUSINESS_PHONE", required = true)
    protected String businessphone;
    @XmlElement(name = "BUSINESS_FAX", required = true)
    protected String businessfax;
    @XmlElement(name = "BUSINESS_EMAIL", required = true)
    protected String businessemail;
    @XmlElement(name = "HS_CODE", required = true)
    protected String hscode;
    @XmlElement(name = "PRODUCT_TYPE_CODE", required = true)
    protected String producttypecode;
    @XmlElement(name = "PRODUCT_NAME", required = true)
    protected String productname;
    @XmlElement(name = "MANUFACTURE_NAME", required = true)
    protected String manufacturename;
    @XmlElement(name = "MANUFACTURE_ADD", required = true)
    protected String manufactureadd;
    @XmlElement(name = "NATION_CODE", required = true)
    protected String nationcode;
    @XmlElement(name = "REGION_FROM", required = true)
    protected String regionfrom;
    @XmlElement(name = "EFFECTIVE_DATE", required = true)
    protected String effectivedate;

    /**
     * Gets the value of the receiptno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIPTNO() {
        return receiptno;
    }

    /**
     * Sets the value of the receiptno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIPTNO(String value) {
        this.receiptno = value;
    }

    /**
     * Gets the value of the provincecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROVINCECODE() {
        return provincecode;
    }

    /**
     * Sets the value of the provincecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROVINCECODE(String value) {
        this.provincecode = value;
    }

    /**
     * Gets the value of the receiptdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIPTDATE() {
        return receiptdate;
    }

    /**
     * Sets the value of the receiptdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIPTDATE(String value) {
        this.receiptdate = value;
    }

    /**
     * Gets the value of the receiptdeptname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIPTDEPTNAME() {
        return receiptdeptname;
    }

    /**
     * Sets the value of the receiptdeptname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIPTDEPTNAME(String value) {
        this.receiptdeptname = value;
    }

    /**
     * Gets the value of the bussinesscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSSINESSCODE() {
        return bussinesscode;
    }

    /**
     * Sets the value of the bussinesscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSSINESSCODE(String value) {
        this.bussinesscode = value;
    }

    /**
     * Gets the value of the businessname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSINESSNAME() {
        return businessname;
    }

    /**
     * Sets the value of the businessname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSINESSNAME(String value) {
        this.businessname = value;
    }

    /**
     * Gets the value of the businessaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSINESSADDRESS() {
        return businessaddress;
    }

    /**
     * Sets the value of the businessaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSINESSADDRESS(String value) {
        this.businessaddress = value;
    }

    /**
     * Gets the value of the businessphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSINESSPHONE() {
        return businessphone;
    }

    /**
     * Sets the value of the businessphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSINESSPHONE(String value) {
        this.businessphone = value;
    }

    /**
     * Gets the value of the businessfax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSINESSFAX() {
        return businessfax;
    }

    /**
     * Sets the value of the businessfax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSINESSFAX(String value) {
        this.businessfax = value;
    }

    /**
     * Gets the value of the businessemail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSINESSEMAIL() {
        return businessemail;
    }

    /**
     * Sets the value of the businessemail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSINESSEMAIL(String value) {
        this.businessemail = value;
    }

    /**
     * Gets the value of the hscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSCODE() {
        return hscode;
    }

    /**
     * Sets the value of the hscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSCODE(String value) {
        this.hscode = value;
    }

    /**
     * Gets the value of the producttypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTTYPECODE() {
        return producttypecode;
    }

    /**
     * Sets the value of the producttypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTTYPECODE(String value) {
        this.producttypecode = value;
    }

    /**
     * Gets the value of the productname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTNAME() {
        return productname;
    }

    /**
     * Sets the value of the productname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTNAME(String value) {
        this.productname = value;
    }

    /**
     * Gets the value of the manufacturename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMANUFACTURENAME() {
        return manufacturename;
    }

    /**
     * Sets the value of the manufacturename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMANUFACTURENAME(String value) {
        this.manufacturename = value;
    }

    /**
     * Gets the value of the manufactureadd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMANUFACTUREADD() {
        return manufactureadd;
    }

    /**
     * Sets the value of the manufactureadd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMANUFACTUREADD(String value) {
        this.manufactureadd = value;
    }

    /**
     * Gets the value of the nationcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONCODE() {
        return nationcode;
    }

    /**
     * Sets the value of the nationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONCODE(String value) {
        this.nationcode = value;
    }

    /**
     * Gets the value of the regionfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGIONFROM() {
        return regionfrom;
    }

    /**
     * Sets the value of the regionfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGIONFROM(String value) {
        this.regionfrom = value;
    }

    /**
     * Gets the value of the effectivedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEFFECTIVEDATE() {
        return effectivedate;
    }

    /**
     * Sets the value of the effectivedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEFFECTIVEDATE(String value) {
        this.effectivedate = value;
    }

}
