//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 02:16:21 PM ICT 
//
package com.viettel.ws.BO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "SEND_RESPONSEDto")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SEND_RESPONSEDto", propOrder = {
    "errorlist"
})
public class SENDRESPONSEDto {

    @XmlElement(name = "ERROR_LIST", required = true)
    protected ERRORLIST errorlist;

    public SENDRESPONSEDto() {
    }

    public SENDRESPONSEDto(ERRORLIST errorlist) {
        this.errorlist = errorlist;
    }

    /**
     * Gets the value of the errorlist property.
     *
     * @return possible object is {@link ERRORLIST }
     *
     */
    public ERRORLIST getERRORLIST() {
        return errorlist;
    }

    /**
     * Sets the value of the errorlist property.
     *
     * @param value allowed object is {@link ERRORLIST }
     *
     */
    public void setERRORLIST(ERRORLIST value) {
        this.errorlist = value;
    }

}
